// 复原纹样数据 — 自动生成于 2026-05-17
export interface RevivalPattern {
  id: string;
  title: string;
  dynasty: string;
  era?: string;
  culture?: string;
  elements?: string[];
  description: string;
  detail?: string;
  src: string;
  thumbSrc?: string;
}

export const revivalPatterns: RevivalPattern[] = [
  {
    "id": "revival-1",
    "title": "卐字地龙纹",
    "dynasty": "元代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/元代-卐字地龙纹.png",
    "thumbSrc": "/images/revival/thumbs/元代-卐字地龙纹.png"
  },
  {
    "id": "revival-2",
    "title": "柿蒂窠",
    "dynasty": "元代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/元代-柿蒂窠.png",
    "thumbSrc": "/images/revival/thumbs/元代-柿蒂窠.png"
  },
  {
    "id": "revival-3",
    "title": "荷塘鸳鸯纹",
    "dynasty": "元代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/元代-荷塘鸳鸯纹.png",
    "thumbSrc": "/images/revival/thumbs/元代-荷塘鸳鸯纹.png"
  },
  {
    "id": "revival-4",
    "title": "落花流水纹",
    "dynasty": "元代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/元代-落花流水纹.png",
    "thumbSrc": "/images/revival/thumbs/元代-落花流水纹.png"
  },
  {
    "id": "revival-5",
    "title": "鸳鸯纹",
    "dynasty": "元代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/元代-鸳鸯纹.png",
    "thumbSrc": "/images/revival/thumbs/元代-鸳鸯纹.png"
  },
  {
    "id": "revival-6",
    "title": "四人飞天",
    "dynasty": "初唐",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/初唐-四人飞天.png",
    "thumbSrc": "/images/revival/thumbs/初唐-四人飞天.png"
  },
  {
    "id": "revival-7",
    "title": "葡萄石榴藻井",
    "dynasty": "初唐",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/初唐-葡萄石榴藻井.png",
    "thumbSrc": "/images/revival/thumbs/初唐-葡萄石榴藻井.png"
  },
  {
    "id": "revival-8",
    "title": "第272窟忍冬藻井",
    "dynasty": "北凉",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/北凉-第272窟忍冬藻井.png",
    "thumbSrc": "/images/revival/thumbs/北凉-第272窟忍冬藻井.png"
  },
  {
    "id": "revival-9",
    "title": "联珠日神纹",
    "dynasty": "北朝",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/北朝-联珠日神纹.png",
    "thumbSrc": "/images/revival/thumbs/北朝-联珠日神纹.png"
  },
  {
    "id": "revival-10",
    "title": "卷草纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-卷草纹.png",
    "thumbSrc": "/images/revival/thumbs/唐代-卷草纹.png"
  },
  {
    "id": "revival-11",
    "title": "团窠对鸟衔瑞草",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-团窠对鸟衔瑞草.png",
    "thumbSrc": "/images/revival/thumbs/唐代-团窠对鸟衔瑞草.png"
  },
  {
    "id": "revival-12",
    "title": "团窠牡丹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-团窠牡丹.png",
    "thumbSrc": "/images/revival/thumbs/唐代-团窠牡丹.png"
  },
  {
    "id": "revival-13",
    "title": "团花狮子纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-团花狮子纹.png",
    "thumbSrc": "/images/revival/thumbs/唐代-团花狮子纹.png"
  },
  {
    "id": "revival-14",
    "title": "团花纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-团花纹.png",
    "thumbSrc": "/images/revival/thumbs/唐代-团花纹.png"
  },
  {
    "id": "revival-15",
    "title": "宝相花",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-宝相花.png",
    "thumbSrc": "/images/revival/thumbs/唐代-宝相花.png"
  },
  {
    "id": "revival-16",
    "title": "对马纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-对马纹.png",
    "thumbSrc": "/images/revival/thumbs/唐代-对马纹.png"
  },
  {
    "id": "revival-17",
    "title": "对鹿联珠团窠",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-对鹿联珠团窠.png",
    "thumbSrc": "/images/revival/thumbs/唐代-对鹿联珠团窠.png"
  },
  {
    "id": "revival-18",
    "title": "小团花纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-小团花纹.png",
    "thumbSrc": "/images/revival/thumbs/唐代-小团花纹.png"
  },
  {
    "id": "revival-19",
    "title": "小宝相花",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-小宝相花.png",
    "thumbSrc": "/images/revival/thumbs/唐代-小宝相花.png"
  },
  {
    "id": "revival-20",
    "title": "折枝卧鹿纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-折枝卧鹿纹.png",
    "thumbSrc": "/images/revival/thumbs/唐代-折枝卧鹿纹.png"
  },
  {
    "id": "revival-21",
    "title": "摩羯纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-摩羯纹.png",
    "thumbSrc": "/images/revival/thumbs/唐代-摩羯纹.png"
  },
  {
    "id": "revival-22",
    "title": "柿蒂纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-柿蒂纹.png",
    "thumbSrc": "/images/revival/thumbs/唐代-柿蒂纹.png"
  },
  {
    "id": "revival-23",
    "title": "海石榴纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-海石榴纹.png",
    "thumbSrc": "/images/revival/thumbs/唐代-海石榴纹.png"
  },
  {
    "id": "revival-24",
    "title": "石榴纹藻井",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-石榴纹藻井.png",
    "thumbSrc": "/images/revival/thumbs/唐代-石榴纹藻井.png"
  },
  {
    "id": "revival-25",
    "title": "簇六添花球路纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-簇六添花球路纹.png",
    "thumbSrc": "/images/revival/thumbs/唐代-簇六添花球路纹.png"
  },
  {
    "id": "revival-26",
    "title": "花鸟纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-花鸟纹.png",
    "thumbSrc": "/images/revival/thumbs/唐代-花鸟纹.png"
  },
  {
    "id": "revival-27",
    "title": "飞鸟小宝花",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-飞鸟小宝花.png",
    "thumbSrc": "/images/revival/thumbs/唐代-飞鸟小宝花.png"
  },
  {
    "id": "revival-28",
    "title": "鸳鸯鎏金盘",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-鸳鸯鎏金盘.png",
    "thumbSrc": "/images/revival/thumbs/唐代-鸳鸯鎏金盘.png"
  },
  {
    "id": "revival-29",
    "title": "兽面纹",
    "dynasty": "商周",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/商周-兽面纹.png",
    "thumbSrc": "/images/revival/thumbs/商周-兽面纹.png"
  },
  {
    "id": "revival-30",
    "title": "涡纹&兽面纹",
    "dynasty": "商周",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/商周-涡纹&兽面纹.png",
    "thumbSrc": "/images/revival/thumbs/商周-涡纹&兽面纹.png"
  },
  {
    "id": "revival-31",
    "title": "蟠龙纹",
    "dynasty": "商周",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/商周-蟠龙纹.png",
    "thumbSrc": "/images/revival/thumbs/商周-蟠龙纹.png"
  },
  {
    "id": "revival-32",
    "title": "一年景纹",
    "dynasty": "宋代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/宋代-一年景纹.png",
    "thumbSrc": "/images/revival/thumbs/宋代-一年景纹.png"
  },
  {
    "id": "revival-33",
    "title": "团窠重莲纹",
    "dynasty": "宋代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/宋代-团窠重莲纹.png",
    "thumbSrc": "/images/revival/thumbs/宋代-团窠重莲纹.png"
  },
  {
    "id": "revival-34",
    "title": "太极鱼鳞纹",
    "dynasty": "宋代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/宋代-太极鱼鳞纹.png",
    "thumbSrc": "/images/revival/thumbs/宋代-太极鱼鳞纹.png"
  },
  {
    "id": "revival-35",
    "title": "开光四季花",
    "dynasty": "宋代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/宋代-开光四季花.png",
    "thumbSrc": "/images/revival/thumbs/宋代-开光四季花.png"
  },
  {
    "id": "revival-36",
    "title": "折枝小花",
    "dynasty": "宋代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/宋代-折枝小花.png",
    "thumbSrc": "/images/revival/thumbs/宋代-折枝小花.png"
  },
  {
    "id": "revival-37",
    "title": "海石榴纹",
    "dynasty": "宋代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/宋代-海石榴纹.png",
    "thumbSrc": "/images/revival/thumbs/宋代-海石榴纹.png"
  },
  {
    "id": "revival-38",
    "title": "罗地龟背纹",
    "dynasty": "宋代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/宋代-罗地龟背纹.png",
    "thumbSrc": "/images/revival/thumbs/宋代-罗地龟背纹.png"
  },
  {
    "id": "revival-39",
    "title": "锁子纹",
    "dynasty": "宋代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/宋代-锁子纹.png",
    "thumbSrc": "/images/revival/thumbs/宋代-锁子纹.png"
  },
  {
    "id": "revival-40",
    "title": "旋涡纹",
    "dynasty": "新石器时代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/新石器时代-旋涡纹.png",
    "thumbSrc": "/images/revival/thumbs/新石器时代-旋涡纹.png"
  },
  {
    "id": "revival-41",
    "title": "鱼纹",
    "dynasty": "新石器时代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/新石器时代-鱼纹.png",
    "thumbSrc": "/images/revival/thumbs/新石器时代-鱼纹.png"
  },
  {
    "id": "revival-42",
    "title": "万寿杂宝八吉祥纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-万寿杂宝八吉祥纹.png",
    "thumbSrc": "/images/revival/thumbs/明代-万寿杂宝八吉祥纹.png"
  },
  {
    "id": "revival-43",
    "title": "五湖四海纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-五湖四海纹.png",
    "thumbSrc": "/images/revival/thumbs/明代-五湖四海纹.png"
  },
  {
    "id": "revival-44",
    "title": "八宝火焰纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-八宝火焰纹.png",
    "thumbSrc": "/images/revival/thumbs/明代-八宝火焰纹.png"
  },
  {
    "id": "revival-45",
    "title": "卐字莲花锦纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-卐字莲花锦纹.png",
    "thumbSrc": "/images/revival/thumbs/明代-卐字莲花锦纹.png"
  },
  {
    "id": "revival-46",
    "title": "四合如意云纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-四合如意云纹.png",
    "thumbSrc": "/images/revival/thumbs/明代-四合如意云纹.png"
  },
  {
    "id": "revival-47",
    "title": "四季花纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-四季花纹.png",
    "thumbSrc": "/images/revival/thumbs/明代-四季花纹.png"
  },
  {
    "id": "revival-48",
    "title": "夔龙球路纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-夔龙球路纹.png",
    "thumbSrc": "/images/revival/thumbs/明代-夔龙球路纹.png"
  },
  {
    "id": "revival-49",
    "title": "摩羯纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-摩羯纹.png",
    "thumbSrc": "/images/revival/thumbs/明代-摩羯纹.png"
  },
  {
    "id": "revival-50",
    "title": "杂宝团花纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-杂宝团花纹.png",
    "thumbSrc": "/images/revival/thumbs/明代-杂宝团花纹.png"
  },
  {
    "id": "revival-51",
    "title": "杂宝纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-杂宝纹.png",
    "thumbSrc": "/images/revival/thumbs/明代-杂宝纹.png"
  },
  {
    "id": "revival-52",
    "title": "绵羊太子纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-绵羊太子纹.png",
    "thumbSrc": "/images/revival/thumbs/明代-绵羊太子纹.png"
  },
  {
    "id": "revival-53",
    "title": "缠枝梅花",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-缠枝梅花.png",
    "thumbSrc": "/images/revival/thumbs/明代-缠枝梅花.png"
  },
  {
    "id": "revival-54",
    "title": "缠枝莲纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-缠枝莲纹.png",
    "thumbSrc": "/images/revival/thumbs/明代-缠枝莲纹.png"
  },
  {
    "id": "revival-55",
    "title": "落花流水纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-落花流水纹.png",
    "thumbSrc": "/images/revival/thumbs/明代-落花流水纹.png"
  },
  {
    "id": "revival-56",
    "title": "葫芦灯纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-葫芦灯纹.png",
    "thumbSrc": "/images/revival/thumbs/明代-葫芦灯纹.png"
  },
  {
    "id": "revival-57",
    "title": "虎镇五毒纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-虎镇五毒纹.png",
    "thumbSrc": "/images/revival/thumbs/明代-虎镇五毒纹.png"
  },
  {
    "id": "revival-58",
    "title": "锦地折枝牡丹纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-锦地折枝牡丹纹.png",
    "thumbSrc": "/images/revival/thumbs/明代-锦地折枝牡丹纹.png"
  },
  {
    "id": "revival-59",
    "title": "云鹤纹",
    "dynasty": "明清",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/明清-云鹤纹.png",
    "thumbSrc": "/images/revival/thumbs/明清-云鹤纹.png"
  },
  {
    "id": "revival-60",
    "title": "蟠螭纹",
    "dynasty": "春秋",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/春秋-蟠螭纹.png",
    "thumbSrc": "/images/revival/thumbs/春秋-蟠螭纹.png"
  },
  {
    "id": "revival-61",
    "title": "乘云绣",
    "dynasty": "汉代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/汉代-乘云绣.png",
    "thumbSrc": "/images/revival/thumbs/汉代-乘云绣.png"
  },
  {
    "id": "revival-62",
    "title": "四神纹",
    "dynasty": "汉代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/汉代-四神纹.png",
    "thumbSrc": "/images/revival/thumbs/汉代-四神纹.png"
  },
  {
    "id": "revival-63",
    "title": "四神纹辅首",
    "dynasty": "汉代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/汉代-四神纹辅首.png",
    "thumbSrc": "/images/revival/thumbs/汉代-四神纹辅首.png"
  },
  {
    "id": "revival-64",
    "title": "大宜子孙安乐锦纹",
    "dynasty": "汉代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/汉代-大宜子孙安乐锦纹.png",
    "thumbSrc": "/images/revival/thumbs/汉代-大宜子孙安乐锦纹.png"
  },
  {
    "id": "revival-65",
    "title": "杯纹菱",
    "dynasty": "汉代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/汉代-杯纹菱.png",
    "thumbSrc": "/images/revival/thumbs/汉代-杯纹菱.png"
  },
  {
    "id": "revival-66",
    "title": "豹首兽面纹",
    "dynasty": "汉代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/汉代-豹首兽面纹.png",
    "thumbSrc": "/images/revival/thumbs/汉代-豹首兽面纹.png"
  },
  {
    "id": "revival-67",
    "title": "鱼蛙纹",
    "dynasty": "汉代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/汉代-鱼蛙纹.png",
    "thumbSrc": "/images/revival/thumbs/汉代-鱼蛙纹.png"
  },
  {
    "id": "revival-68",
    "title": "龟背填花纹",
    "dynasty": "汉代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/汉代-龟背填花纹.png",
    "thumbSrc": "/images/revival/thumbs/汉代-龟背填花纹.png"
  },
  {
    "id": "revival-69",
    "title": "三多纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-三多纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-三多纹.png"
  },
  {
    "id": "revival-70",
    "title": "云蝠纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-云蝠纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-云蝠纹.png"
  },
  {
    "id": "revival-71",
    "title": "五福捧寿纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-五福捧寿纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-五福捧寿纹.png"
  },
  {
    "id": "revival-72",
    "title": "五蝠缠枝花纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-五蝠缠枝花纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-五蝠缠枝花纹.png"
  },
  {
    "id": "revival-73",
    "title": "八吉祥团花纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-八吉祥团花纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-八吉祥团花纹.png"
  },
  {
    "id": "revival-74",
    "title": "兽面纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-兽面纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-兽面纹.png"
  },
  {
    "id": "revival-75",
    "title": "兽面鳞纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-兽面鳞纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-兽面鳞纹.png"
  },
  {
    "id": "revival-76",
    "title": "冰裂梅花纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-冰裂梅花纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-冰裂梅花纹.png"
  },
  {
    "id": "revival-77",
    "title": "几何蝠纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-几何蝠纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-几何蝠纹.png"
  },
  {
    "id": "revival-78",
    "title": "勾莲纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-勾莲纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-勾莲纹.png"
  },
  {
    "id": "revival-79",
    "title": "十二章纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-十二章纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-十二章纹.png"
  },
  {
    "id": "revival-80",
    "title": "博古纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-博古纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-博古纹.png"
  },
  {
    "id": "revival-81",
    "title": "卷草莲纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-卷草莲纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-卷草莲纹.png"
  },
  {
    "id": "revival-82",
    "title": "双狮戏绣球",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-双狮戏绣球.png",
    "thumbSrc": "/images/revival/thumbs/清代-双狮戏绣球.png"
  },
  {
    "id": "revival-83",
    "title": "双龙海水江崖",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-双龙海水江崖.png",
    "thumbSrc": "/images/revival/thumbs/清代-双龙海水江崖.png"
  },
  {
    "id": "revival-84",
    "title": "和合二仙纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-和合二仙纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-和合二仙纹.png"
  },
  {
    "id": "revival-85",
    "title": "夔凤纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-夔凤纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-夔凤纹.png"
  },
  {
    "id": "revival-86",
    "title": "夔龙团纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-夔龙团纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-夔龙团纹.png"
  },
  {
    "id": "revival-87",
    "title": "大雅斋花鸟纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-大雅斋花鸟纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-大雅斋花鸟纹.png"
  },
  {
    "id": "revival-88",
    "title": "宫灯云凤纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-宫灯云凤纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-宫灯云凤纹.png"
  },
  {
    "id": "revival-89",
    "title": "宫灯纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-宫灯纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-宫灯纹.png"
  },
  {
    "id": "revival-90",
    "title": "山水纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-山水纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-山水纹.png"
  },
  {
    "id": "revival-91",
    "title": "折枝花蝶纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-折枝花蝶纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-折枝花蝶纹.png"
  },
  {
    "id": "revival-92",
    "title": "暗八仙纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-暗八仙纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-暗八仙纹.png"
  },
  {
    "id": "revival-93",
    "title": "松鼠葡萄纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-松鼠葡萄纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-松鼠葡萄纹.png"
  },
  {
    "id": "revival-94",
    "title": "果品蝠纹天华锦",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-果品蝠纹天华锦.png",
    "thumbSrc": "/images/revival/thumbs/清代-果品蝠纹天华锦.png"
  },
  {
    "id": "revival-95",
    "title": "海水江崖纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-海水江崖纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-海水江崖纹.png"
  },
  {
    "id": "revival-96",
    "title": "狮子纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-狮子纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-狮子纹.png"
  },
  {
    "id": "revival-97",
    "title": "球路双龙纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-球路双龙纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-球路双龙纹.png"
  },
  {
    "id": "revival-98",
    "title": "皮球小团花",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-皮球小团花.png",
    "thumbSrc": "/images/revival/thumbs/清代-皮球小团花.png"
  },
  {
    "id": "revival-99",
    "title": "石榴牡丹纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-石榴牡丹纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-石榴牡丹纹.png"
  },
  {
    "id": "revival-100",
    "title": "缠枝八吉祥",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-缠枝八吉祥.png",
    "thumbSrc": "/images/revival/thumbs/清代-缠枝八吉祥.png"
  },
  {
    "id": "revival-101",
    "title": "缠枝八吉祥纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-缠枝八吉祥纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-缠枝八吉祥纹.png"
  },
  {
    "id": "revival-102",
    "title": "缠枝四季花纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-缠枝四季花纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-缠枝四季花纹.png"
  },
  {
    "id": "revival-103",
    "title": "缠枝牡丹纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-缠枝牡丹纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-缠枝牡丹纹.png"
  },
  {
    "id": "revival-104",
    "title": "缠枝花果纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-缠枝花果纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-缠枝花果纹.png"
  },
  {
    "id": "revival-105",
    "title": "葫芦纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-葫芦纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-葫芦纹.png"
  },
  {
    "id": "revival-106",
    "title": "蕉叶纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-蕉叶纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-蕉叶纹.png"
  },
  {
    "id": "revival-107",
    "title": "蕉叶缠枝花纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-蕉叶缠枝花纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-蕉叶缠枝花纹.png"
  },
  {
    "id": "revival-108",
    "title": "蝉纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-蝉纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-蝉纹.png"
  },
  {
    "id": "revival-109",
    "title": "西番莲蝠纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-西番莲蝠纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-西番莲蝠纹.png"
  },
  {
    "id": "revival-110",
    "title": "金鱼纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-金鱼纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-金鱼纹.png"
  },
  {
    "id": "revival-111",
    "title": "锦地团花",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-锦地团花.png",
    "thumbSrc": "/images/revival/thumbs/清代-锦地团花.png"
  },
  {
    "id": "revival-112",
    "title": "锦地开光花蝶纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-锦地开光花蝶纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-锦地开光花蝶纹.png"
  },
  {
    "id": "revival-113",
    "title": "鹤纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-鹤纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-鹤纹.png"
  },
  {
    "id": "revival-114",
    "title": "麒麟纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-麒麟纹.png",
    "thumbSrc": "/images/revival/thumbs/清代-麒麟纹.png"
  },
  {
    "id": "revival-115",
    "title": "龙纹柿蒂窠",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-龙纹柿蒂窠.png",
    "thumbSrc": "/images/revival/thumbs/清代-龙纹柿蒂窠.png"
  },
  {
    "id": "revival-116",
    "title": "菱形天华锦（成都博物馆）",
    "dynasty": "现代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/现代-菱形天华锦（成都博物馆）.png",
    "thumbSrc": "/images/revival/thumbs/现代-菱形天华锦（成都博物馆）.png"
  },
  {
    "id": "revival-117",
    "title": "第319窟宝相花藻井",
    "dynasty": "盛唐",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/盛唐-第319窟宝相花藻井.png",
    "thumbSrc": "/images/revival/thumbs/盛唐-第319窟宝相花藻井.png"
  },
  {
    "id": "revival-118",
    "title": "波曲纹",
    "dynasty": "西周",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/西周-波曲纹.png",
    "thumbSrc": "/images/revival/thumbs/西周-波曲纹.png"
  },
  {
    "id": "revival-119",
    "title": "窃曲纹",
    "dynasty": "西周",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/西周-窃曲纹.png",
    "thumbSrc": "/images/revival/thumbs/西周-窃曲纹.png"
  },
  {
    "id": "revival-120",
    "title": "第285窟莲花忍冬藻井",
    "dynasty": "西魏",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/西魏-第285窟莲花忍冬藻井.png",
    "thumbSrc": "/images/revival/thumbs/西魏-第285窟莲花忍冬藻井.png"
  },
  {
    "id": "revival-121",
    "title": "秋山鹿纹",
    "dynasty": "辽代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/辽代-秋山鹿纹.png",
    "thumbSrc": "/images/revival/thumbs/辽代-秋山鹿纹.png"
  },
  {
    "id": "revival-122",
    "title": "鱼纹",
    "dynasty": "辽代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/辽代-鱼纹.png",
    "thumbSrc": "/images/revival/thumbs/辽代-鱼纹.png"
  },
  {
    "id": "revival-123",
    "title": "双凤朝阳纹",
    "dynasty": "近代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/近代-双凤朝阳纹.png",
    "thumbSrc": "/images/revival/thumbs/近代-双凤朝阳纹.png"
  },
  {
    "id": "revival-124",
    "title": "春水滴珠窠",
    "dynasty": "金代",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/金代-春水滴珠窠.png",
    "thumbSrc": "/images/revival/thumbs/金代-春水滴珠窠.png"
  },
  {
    "id": "revival-125",
    "title": "双头鸟纹",
    "dynasty": "魏晋南北朝",
    "era": "",
    "culture": "",
    "elements": [],
    "description": "",
    "detail": "",
    "src": "/images/revival/魏晋南北朝-双头鸟纹.png",
    "thumbSrc": "/images/revival/thumbs/魏晋南北朝-双头鸟纹.png"
  }
];
