// 复原纹样数据 — 137件 | 元代已恢复
export interface RevivalPattern {
  id: string;
  title: string;
  dynasty: string;
  era?: string;
  culture?: string;
  structure?: string;
  structureL1?: string;
  structureL2?: string;
  elements?: string[];
  colors?: string[];
  description: string;
  detail?: string;
  src: string;
  thumbSrc?: string;
  isNew?: boolean;
  nonCommercial?: boolean; // 无商业处理（仅供学习展示，无购买）
}

export const revivalPatterns: RevivalPattern[] = [
  {
    "id": "revival-6",
    "title": "四人飞天",
    "dynasty": "初唐",
    "era": "",
    "culture": "",
    "elements": ["飞天", "莲花", "华盖"],
    "description": "",
    "detail": "",
    "src": "/images/revival/初唐-四人飞天.webp",
    "thumbSrc": "/images/revival/thumbs/初唐-四人飞天.png",
    "structure": "单独/自由式",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-7",
    "title": "葡萄石榴藻井",
    "dynasty": "初唐",
    "era": "",
    "culture": "",
    "elements": ["葡萄纹", "石榴纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/初唐-葡萄石榴藻井.webp",
    "thumbSrc": "/images/revival/thumbs/初唐-葡萄石榴藻井.png",
    "structure": "适合/对称式",
  
    "structureL1": "单独纹样",
    "structureL2": "适合纹样",
  },
  {
    "id": "revival-8",
    "title": "第272窟忍冬藻井",
    "dynasty": "北凉",
    "era": "",
    "culture": "此窟的藻井来自北凉时期，是莫高窟现存最早的「斗四藻井」之一，画风依旧带着浓郁的异域风情。此时的飞天形象依旧是男性，画法也使用了「凹凸晕染法」来塑造五官的立体感。忍冬元素被反复运用，象征生生不息，忍冬与飞天，共同营造充满异域风情的天宫情景。",
    "elements": ["忍冬", "飞天", "莲花"],
    "description": "",
    "detail": "",
    "src": "/images/revival/北凉-第272窟忍冬藻井.webp",
    "nonCommercial": true,
    "thumbSrc": "/images/revival/thumbs/北凉-第272窟忍冬藻井.png",
    "structure": "适合/离心式/角隅式",
  
    "structureL1": "单独纹样",
    "structureL2": "适合纹样",
  },
  {
    "id": "revival-9",
    "title": "联珠日神纹",
    "dynasty": "北朝",
    "era": "",
    "culture": "",
    "elements": ["联珠纹", "日神纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/北朝-联珠日神纹.webp",
    "thumbSrc": "/images/revival/thumbs/北朝-联珠日神纹.png",
    "structure": "四方连续/几何连缀",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-10",
    "title": "卷草纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "分别来自西魏432窟、初唐217窟、中唐158窟、晚唐9窟。从西魏的质朴西域风，到初唐的生机勃勃，到中唐的严谨雅致，再到晚唐的纤细繁缛，可以看到卷草纹被刚传入吸收、到发展、后又程式化的过程。",
    "elements": ["卷草纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-卷草纹.webp",
    "nonCommercial": true,
    "thumbSrc": "/images/revival/thumbs/唐代-卷草纹.png",
    "structure": "二方连续/波线式",
  
    "structureL1": "二方连续",
    "structureL2": "波线式",
  },
  {
    "id": "revival-11",
    "title": "团窠对鸟衔瑞草",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": ["对鸟团窠", "花卉纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-团窠对鸟衔瑞草.webp",
    "thumbSrc": "/images/revival/thumbs/唐代-团窠对鸟衔瑞草.png",
    "structure": "四方连续/规则散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-12",
    "title": "团窠牡丹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": ["牡丹纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-团窠牡丹.webp",
    "thumbSrc": "/images/revival/thumbs/唐代-团窠牡丹.png",
    "structure": "四方连续/错位散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-13",
    "title": "团花狮子纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": ["狮子纹", "团花纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-团花狮子纹.webp",
    "thumbSrc": "/images/revival/thumbs/唐代-团花狮子纹.png",
    "structure": "四方连续/规则散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-14",
    "title": "团花纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": ["团花纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-团花纹.webp",
    "thumbSrc": "/images/revival/thumbs/唐代-团花纹.png",
    "structure": "四方连续/规则散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-15",
    "title": "宝相花",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": ["宝相花", "花卉纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-宝相花.webp",
    "thumbSrc": "/images/revival/thumbs/唐代-宝相花.png",
    "structure": "单独/自由/角隅/放射式",
  
    "structureL1": "单独纹样",
    "structureL2": "角隅纹样",
  },
  {
    "id": "revival-16",
    "title": "对马纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": ["联珠对马纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-对马纹.webp",
    "thumbSrc": "/images/revival/thumbs/唐代-对马纹.png",
    "structure": "四方连续/几何连缀",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-17",
    "title": "对鹿联珠团窠",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": ["团窠对鹿纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-对鹿联珠团窠.webp",
    "thumbSrc": "/images/revival/thumbs/唐代-对鹿联珠团窠.png",
    "structure": "四方连续/规则散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-18",
    "title": "小团花纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": ["联珠小团花"],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-小团花纹.webp",
    "thumbSrc": "/images/revival/thumbs/唐代-小团花纹.png",
    "structure": "四方连续/规则散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-19",
    "title": "小宝相花",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": ["宝相花"],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-小宝相花.webp",
    "thumbSrc": "/images/revival/thumbs/唐代-小宝相花.png",
    "structure": "四方连续/规则散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-20",
    "title": "折枝卧鹿纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": ["鹿纹", "十字折枝花纹", "石榴纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-折枝卧鹿纹.webp",
    "thumbSrc": "/images/revival/thumbs/唐代-折枝卧鹿纹.png",
    "structure": "单独/适合/均衡",
  
    "structureL1": "单独纹样",
    "structureL2": "适合纹样",
  },
  {
    "id": "revival-21",
    "title": "摩羯纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
"structure": "单独/适合/均衡喜相逢",
    "elements": ["折枝花纹", "摩羯纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-摩羯纹.webp",
    "thumbSrc": "/images/revival/thumbs/唐代-摩羯纹.png",
  
    "structureL1": "单独纹样",
    "structureL2": "适合纹样",
  },
  {
    "id": "revival-22",
    "title": "柿蒂纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": ["柿蒂纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-柿蒂纹.webp",
    "thumbSrc": "/images/revival/thumbs/唐代-柿蒂纹.png",
    "structure": "四方连续/规则散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-23",
    "title": "海石榴纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": ["海石榴纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-海石榴纹.webp",
    "thumbSrc": "/images/revival/thumbs/唐代-海石榴纹.png",
    "structure": "单独/适合/对称式",
  
    "structureL1": "单独纹样",
    "structureL2": "适合纹样",
  },
  {
    "id": "revival-24",
    "title": "石榴纹藻井",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": ["石榴纹", "方形宝相花纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-石榴纹藻井.webp",
    "nonCommercial": true,
    "thumbSrc": "/images/revival/thumbs/唐代-石榴纹藻井.png",
    "structure": "单独/适合/角隅式/离心式",
  
    "structureL1": "单独纹样",
    "structureL2": "适合纹样",
  },
  {
    "id": "revival-25",
    "title": "簇六添花球路纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
"structure": "四方连续/几何连缀",
    "elements": ["球路纹", "小花纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-簇六添花球路纹.webp",
    "thumbSrc": "/images/revival/thumbs/唐代-簇六添花球路纹.png",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-26",
    "title": "花鸟纹",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": ["花卉纹", "鸟纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-花鸟纹.webp",
    "thumbSrc": "/images/revival/thumbs/唐代-花鸟纹.png",
    "structure": "单独/自由/对称",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-27",
    "title": "飞鸟小宝花",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": ["方形小宝相纹", "鸟纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-飞鸟小宝花.webp",
    "thumbSrc": "/images/revival/thumbs/唐代-飞鸟小宝花.png",
    "structure": "四方连续/错位散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-28",
    "title": "鸳鸯鎏金盘",
    "dynasty": "唐代",
    "era": "",
    "culture": "",
    "elements": ["鸳鸯纹", "石榴纹", "花卉纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/唐代-鸳鸯鎏金盘.webp",
    "thumbSrc": "/images/revival/thumbs/唐代-鸳鸯鎏金盘.png",
    "structure": "单独/适合/对称+均衡",
  
    "structureL1": "单独纹样",
    "structureL2": "适合纹样",
  },
  {
    "id": "revival-29",
    "title": "兽面纹",
    "dynasty": "商周",
    "era": "",
    "culture": "",
    "elements": ["兽面纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/商周-兽面纹.webp",
    "thumbSrc": "/images/revival/thumbs/商周-兽面纹.png",
    "structure": "单独/自由式",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-30",
    "title": "涡纹&兽面纹",
    "dynasty": "商周",
    "era": "",
    "culture": "",
    "elements": ["涡纹", "兽面纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/商周-涡纹&兽面纹.webp",
    "thumbSrc": "/images/revival/thumbs/商周-涡纹&兽面纹.png",
    "structure": "二方连续/散点式",
  
    "structureL1": "二方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-31",
    "title": "蟠龙纹",
    "dynasty": "商周",
    "era": "",
    "culture": "",
    "elements": ["蟠龙纹", "鱼纹", "地纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/商周-蟠龙纹.webp",
    "thumbSrc": "/images/revival/thumbs/商周-蟠龙纹.png",
    "structure": "单独/自由式重叠式",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-32",
    "title": "一年景纹",
    "dynasty": "宋代",
    "era": "",
    "culture": "",
"structure": "单独/自由式",
    "elements": ["花卉纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/宋代-一年景纹.webp",
    "thumbSrc": "/images/revival/thumbs/宋代-一年景纹.png",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-33",
    "title": "团窠重莲纹",
    "dynasty": "宋代",
    "era": "",
    "culture": "",
    "elements": ["莲纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/宋代-团窠重莲纹.webp",
    "thumbSrc": "/images/revival/thumbs/宋代-团窠重莲纹.png",
    "structure": "四方连续/规则散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-34",
    "title": "太极鱼鳞纹",
    "dynasty": "宋代",
    "era": "",
    "culture": "太极鱼做了变化，使得线条形成了波浪形，与底纹鱼鳞纹形成的小波浪呼应。",
    "elements": ["鱼鳞纹", "太极鱼纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/宋代-太极鱼鳞纹.webp",
    "nonCommercial": true,
    "thumbSrc": "/images/revival/thumbs/宋代-太极鱼鳞纹.png",
    "structure": "四方连续/重叠式",
  
    "structureL1": "四方连续",
    "structureL2": "重叠式",
  },
  {
    "id": "revival-35",
    "title": "开光四季花",
    "dynasty": "宋代",
    "era": "",
    "culture": "",
"structure": "二方连续/散点",
    "elements": ["四季花纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/宋代-开光四季花.webp",
    "thumbSrc": "/images/revival/thumbs/宋代-开光四季花.png",
  
    "structureL1": "二方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-36",
    "title": "折枝小花",
    "dynasty": "宋代",
    "era": "",
    "culture": "",
    "elements": ["折枝花纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/宋代-折枝小花.webp",
    "thumbSrc": "/images/revival/thumbs/宋代-折枝小花.png",
    "structure": "四方连续/规则散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-37",
    "title": "海石榴纹",
    "dynasty": "宋代",
    "era": "",
    "culture": "",
    "elements": [
      "石榴"
    ],
    "description": "",
    "detail": "",
    "src": "/images/revival/宋代-海石榴纹.webp",
    "thumbSrc": "/images/revival/thumbs/宋代-海石榴纹.png",
    "structure": "植物造型",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-38",
    "title": "罗地龟背纹",
    "dynasty": "宋代",
    "era": "",
    "culture": "",
    "elements": ["小团花"],
    "description": "",
    "detail": "",
    "src": "/images/revival/宋代-罗地龟背纹.webp",
    "thumbSrc": "/images/revival/thumbs/宋代-罗地龟背纹.png",
    "structure": "四方连续/网格连缀",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-39",
    "title": "锁子纹",
    "dynasty": "宋代",
    "era": "",
    "culture": "",
"structure": "四方连续/网格连缀",
    "elements": ["锁子纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/宋代-锁子纹.webp",
    "thumbSrc": "/images/revival/thumbs/宋代-锁子纹.png",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-40",
    "title": "旋涡纹",
    "dynasty": "新石器时代",
    "era": "",
    "culture": "",
"structure": "二方连续/散点式",
    "elements": ["旋涡纹", "变形鸟纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/新石器时代-旋涡纹.webp",
    "thumbSrc": "/images/revival/thumbs/新石器时代-旋涡纹.png",
  
    "structureL1": "二方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-41",
    "title": "鱼纹",
    "dynasty": "新石器时代",
    "era": "",
    "culture": "",
    "elements": ["鱼纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/新石器时代-鱼纹.webp",
    "thumbSrc": "/images/revival/thumbs/新石器时代-鱼纹.png",
    "structure": "二方连续/散点式",
  
    "structureL1": "二方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-42",
    "title": "万寿杂宝八吉祥纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
"structure": "四方连续/不规则散点",
    "elements": ["文字纹", "八吉祥纹", "杂宝纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-万寿杂宝八吉祥纹.webp",
    "thumbSrc": "/images/revival/thumbs/明代-万寿杂宝八吉祥纹.png",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-43",
    "title": "五湖四海纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
"structure": "四方连续/错位散点",
    "elements": ["葫芦纹", "杂宝纹", "寿字纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-五湖四海纹.webp",
    "thumbSrc": "/images/revival/thumbs/明代-五湖四海纹.png",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-44",
    "title": "八宝火焰纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
"structure": "四方连续/规则散点",
    "elements": ["火焰纹", "杂宝纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-八宝火焰纹.webp",
    "thumbSrc": "/images/revival/thumbs/明代-八宝火焰纹.png",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-45",
    "title": "卐字莲花锦纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": ["莲纹", "卐字纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-卐字莲花锦纹.webp",
    "thumbSrc": "/images/revival/thumbs/明代-卐字莲花锦纹.png",
    "structure": "四方连续/几何连缀",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-46",
    "title": "四合如意云纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": ["云纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-四合如意云纹.webp",
    "thumbSrc": "/images/revival/thumbs/明代-四合如意云纹.png",
    "structure": "四方连续/错位散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-47",
    "title": "四季花纹",
    "dynasty": "明代",
    "era": "",
    "culture": "以经典的牡丹、菊花、莲花、梅花为元素，分别代表春夏秋冬，寓意看尽四季美好，是一年景纹样的延伸。也符合中国审美中追求意境、不问四时的审美情趣。",
"structure": "四方连续/缠绕式连缀",
    "elements": ["莲花纹", "牡丹纹", "菊花纹", "茶花纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-四季花纹.webp",
    "nonCommercial": true,
    "thumbSrc": "/images/revival/thumbs/明代-四季花纹.png",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-48",
    "title": "夔龙球路纹",
    "dynasty": "明代",
    "era": "",
    "culture": "以规矩的几何纹作为地纹，上用大小球路相切、相交的形式形成球路纹锦的经典骨架，球路骨架之间用小花卉点缀，内填夔龙纹。纹样精致庄重。",
    "elements": ["锦地纹", "球路纹", "夔龙纹", "如意纹", "小团花纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-夔龙球路纹.webp",
    "nonCommercial": true,
    "thumbSrc": "/images/revival/thumbs/明代-夔龙球路纹.png",
    "structure": "四方连续/几何连缀",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-49",
    "title": "摩羯纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": [
      "传统纹样"
    ],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-摩羯纹.webp",
    "thumbSrc": "/images/revival/thumbs/明代-摩羯纹.png",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-50",
    "title": "杂宝团花纹",
    "dynasty": "明代",
    "era": "",
    "culture": "以经典的杂宝纹样围绕牡丹花卉形成团花状，福气满满，旁又点缀四季花纹，四季尽收眼底。纹样处理得小巧别致，给人以清丽俏皮之感。",
    "elements": ["花卉纹", "杂宝纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-杂宝团花纹.webp",
    "nonCommercial": true,
    "thumbSrc": "/images/revival/thumbs/明代-杂宝团花纹.png",
    "structure": "四方连续/不规则散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-51",
    "title": "杂宝纹",
    "dynasty": "明代",
    "era": "",
    "culture": "以经典杂宝珊瑚、犀牛角、象牙、方胜、摩尼珠、金钱、如意元素组成圆团型，让原本零散的小元素变成了更加端庄大气的团型杂宝纹，寓意也更多了圆满福气。除此之外，杂宝纹还包含佛八宝、八音纹、八仙纹等多种从其他纹样中吸收过来的元素，杂代表着更多更丰富的好彩头，契合中国人喜欢十全十美的美好希望。",
"structure": "四方连续/错位散点",
    "elements": ["杂宝纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-杂宝纹.webp",
    "nonCommercial": true,
    "thumbSrc": "/images/revival/thumbs/明代-杂宝纹.png",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-52",
    "title": "绵羊太子纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": ["绵羊太子纹", "梅花纹", "杂宝纹", "山茶花纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-绵羊太子纹.webp",
    "thumbSrc": "/images/revival/thumbs/明代-绵羊太子纹.png",
    "structure": "四方连续/不规则散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-53",
    "title": "缠枝梅花",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": ["梅花纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-缠枝梅花.webp",
    "nonCommercial": true,
    "thumbSrc": "/images/revival/thumbs/明代-缠枝梅花.png",
    "structure": "四方连续/波形连缀",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-54",
    "title": "缠枝莲纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": ["莲纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-缠枝莲纹.webp",
    "thumbSrc": "/images/revival/thumbs/明代-缠枝莲纹.png",
    "structure": "四方连续/波形连缀",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-55",
    "title": "落花流水纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": ["变型水纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-落花流水纹.webp",
    "thumbSrc": "/images/revival/thumbs/明代-落花流水纹.png",
    "structure": "四方连续/错位散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-56",
    "title": "葫芦灯纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
"structure": "四方连续/规则散点",
    "elements": ["葫芦灯纹", "牡丹纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-葫芦灯纹.webp",
    "thumbSrc": "/images/revival/thumbs/明代-葫芦灯纹.png",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-57",
    "title": "虎镇五毒纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": ["五毒纹", "艾草纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-虎镇五毒纹.webp",
    "thumbSrc": "/images/revival/thumbs/明代-虎镇五毒纹.png",
    "structure": "四方连续/不规则散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-58",
    "title": "锦地折枝牡丹纹",
    "dynasty": "明代",
    "era": "",
    "culture": "",
    "elements": ["牡丹纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/明代-锦地折枝牡丹纹.webp",
    "thumbSrc": "/images/revival/thumbs/明代-锦地折枝牡丹纹.png",
    "structure": "四方连续/重叠式",
  
    "structureL1": "四方连续",
    "structureL2": "重叠式",
  },
  {
    "id": "revival-59",
    "title": "云鹤纹",
    "dynasty": "明清",
    "era": "",
    "culture": "",
    "elements": ["仙鹤纹", "云纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/明清-云鹤纹.webp",
    "thumbSrc": "/images/revival/thumbs/明清-云鹤纹.png",
    "structure": "四方连续/错位散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-60",
    "title": "蟠螭纹",
    "dynasty": "春秋",
    "era": "",
    "culture": "",
"structure": "二方连续/单散点",
    "elements": ["蟠螭"],
    "description": "",
    "detail": "",
    "src": "/images/revival/春秋-蟠螭纹.webp",
    "thumbSrc": "/images/revival/thumbs/春秋-蟠螭纹.png",
  
    "structureL1": "二方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-61",
    "title": "乘云绣",
    "dynasty": "汉代",
    "era": "",
    "culture": "",
    "elements": ["云纹", "变型鸟纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/汉代-乘云绣.webp",
    "thumbSrc": "/images/revival/thumbs/汉代-乘云绣.png",
    "structure": "四方连续/自由缠绕连缀",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-62",
    "title": "四神纹",
    "dynasty": "汉代",
    "era": "",
    "culture": "",
"structure": "单独/自由式",
    "elements": ["龙纹", "玄武纹", "朱雀纹", "羽人纹", "怪兽纹", "虎纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/汉代-四神纹.webp",
    "thumbSrc": "/images/revival/thumbs/汉代-四神纹.png",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-63",
    "title": "四神纹辅首",
    "dynasty": "汉代",
    "era": "",
    "culture": "",
"structure": "适合/均衡式",
    "elements": ["龙纹", "朱雀纹", "玄武纹", "虎纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/汉代-四神纹辅首.webp",
    "thumbSrc": "/images/revival/thumbs/汉代-四神纹辅首.png",
  
    "structureL1": "单独纹样",
    "structureL2": "适合纹样",
  },
  {
    "id": "revival-64",
    "title": "大宜子孙安乐锦纹",
    "dynasty": "汉代",
    "era": "",
    "culture": "",
    "elements": ["云纹", "虎纹", "文字纹", "鸟纹", "龙纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/汉代-大宜子孙安乐锦纹.webp",
    "thumbSrc": "/images/revival/thumbs/汉代-大宜子孙安乐锦纹.png",
    "structure": "二方连续/散点式",
  
    "structureL1": "二方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-65",
    "title": "杯纹菱",
    "dynasty": "汉代",
    "era": "",
    "culture": "",
    "elements": ["杯纹菱"],
    "description": "",
    "detail": "",
    "src": "/images/revival/汉代-杯纹菱.webp",
    "thumbSrc": "/images/revival/thumbs/汉代-杯纹菱.png",
    "structure": "四方连续/规则散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-66",
    "title": "豹首兽面纹",
    "dynasty": "汉代",
    "era": "",
    "culture": "",
    "elements": ["兽面纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/汉代-豹首兽面纹.webp",
    "thumbSrc": "/images/revival/thumbs/汉代-豹首兽面纹.png",
    "structure": "四方连续/单散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-67",
    "title": "鱼蛙纹",
    "dynasty": "汉代",
    "era": "",
    "culture": "鱼蛙在汉代代表了吉祥寓意，鱼多子、丰饶富足，蟾蜍（蛙）更是与月亮、兔子成为了西王母不死灵药传说的关键元素。鱼蛙纹代表着人们最原始的生命力，期望生生不息、丰饶富足的美好憧憬。",
    "elements": ["鱼纹", "蛙纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/汉代-鱼蛙纹.webp",
    "nonCommercial": true,
    "thumbSrc": "/images/revival/thumbs/汉代-鱼蛙纹.png",
    "structure": "四方连续/错位散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-68",
    "title": "龟背填花纹",
    "dynasty": "汉代",
    "era": "",
    "culture": "",
    "elements": ["龟背纹", "卐字纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/汉代-龟背填花纹.webp",
    "thumbSrc": "/images/revival/thumbs/汉代-龟背填花纹.png",
    "structure": "四方连续/几何连缀",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-69",
    "title": "三多纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
"structure": "四方连续/重叠式",
    "elements": ["三多纹", "连钱纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-三多纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-三多纹.png",
  
    "structureL1": "四方连续",
    "structureL2": "重叠式",
  },
  {
    "id": "revival-70",
    "title": "云蝠纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["蝙蝠纹", "云纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-云蝠纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-云蝠纹.png",
    "structure": "四方连续/不规则散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-71",
    "title": "五福捧寿纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
"structure": "单独/自由式",
    "elements": ["蝙蝠纹", "寿字纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-五福捧寿纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-五福捧寿纹.png",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-72",
    "title": "五蝠缠枝花纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["云纹", "蝙蝠纹", "寿字纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-五蝠缠枝花纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-五蝠缠枝花纹.png",
    "structure": "单独/适合/向心式",
  
    "structureL1": "单独纹样",
    "structureL2": "适合纹样",
  },
  {
    "id": "revival-73",
    "title": "八吉祥团花纹",
    "dynasty": "清代",
    "era": "",
    "culture": "佛教八宝元素，包括法轮、法螺、宝伞（白盖或华盖）、宝幢、莲花、宝瓶、双鱼和盘长（也称吉祥结）。八吉祥代表遮蔽魔障、解脱、佛法远播、到达彼岸、佛法无边等寓意，以八吉祥汇成团花型，寓意美满吉祥。",
    "elements": ["八吉祥纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-八吉祥团花纹.webp",
    "nonCommercial": true,
    "thumbSrc": "/images/revival/thumbs/清代-八吉祥团花纹.png",
    "structure": "四方连续/规则散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-74",
    "title": "兽面纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": [
      "传统纹样"
    ],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-兽面纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-兽面纹.png",
    "structure": "瑞兽造型",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-75",
    "title": "兽面鳞纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["鱼鳞纹", "回型纹", "兽面纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-兽面鳞纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-兽面鳞纹.png",
    "structure": "四方连续/网格连缀  二方连续/散点式",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-76",
    "title": "冰裂梅花纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["冰裂纹", "梅花纹", "开光纹", "云雷纹", "蕉叶纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-冰裂梅花纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-冰裂梅花纹.png",
    "structure": "四方连续/重叠式    适合/开光式",
  
    "structureL1": "四方连续",
    "structureL2": "重叠式",
  },
  {
    "id": "revival-77",
    "title": "几何蝠纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["龟背纹", "蝙蝠纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-几何蝠纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-几何蝠纹.png",
    "structure": "四方连续/网格式连缀",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-78",
    "title": "勾莲纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["莲纹", "如意纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-勾莲纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-勾莲纹.png",
    "structure": "二方连续/波线式",
  
    "structureL1": "二方连续",
    "structureL2": "波线式",
  },
  {
    "id": "revival-79",
    "title": "十二章纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
"structure": "单独/自由式",
    "elements": ["十二章纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-十二章纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-十二章纹.png",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-80",
    "title": "博古纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
"structure": "单独/自由式",
    "elements": ["博古纹", "杂宝纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-博古纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-博古纹.png",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-81",
    "title": "卷草莲纹",
    "dynasty": "清代",
    "era": "",
    "culture": "以婉转缠绕的卷草作为搭配，莲纹分别以角隅和适合的形式呈现，外又装饰卷草与夔龙（或蟠螭）作为呼应，繁缛精致，端庄华贵。",
    "elements": ["卷草纹", "夔龙纹", "莲纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-卷草莲纹.webp",
    "nonCommercial": true,
    "thumbSrc": "/images/revival/thumbs/清代-卷草莲纹.png",
    "structure": "单独/适合对称/角隅对称",
  
    "structureL1": "单独纹样",
    "structureL2": "适合纹样",
  },
  {
    "id": "revival-82",
    "title": "双狮戏绣球",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["狮子纹", "夔龙纹", "云纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-双狮戏绣球.webp",
    "thumbSrc": "/images/revival/thumbs/清代-双狮戏绣球.png",
    "structure": "单独/适合/角隅",
  
    "structureL1": "单独纹样",
    "structureL2": "适合纹样",
  },
  {
    "id": "revival-83",
    "title": "双龙海水江崖",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["龙纹", "云纹", "海水江崖纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-双龙海水江崖.webp",
    "thumbSrc": "/images/revival/thumbs/清代-双龙海水江崖.png",
    "structure": "单独/对称式",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-84",
    "title": "和合二仙纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
"structure": "单独/自由式",
    "elements": ["和合二仙纹", "莲纹", "蟾蜍纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-和合二仙纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-和合二仙纹.png",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-85",
    "title": "夔凤纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["夔凤纹", "缠枝花纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-夔凤纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-夔凤纹.png",
    "structure": "单独/自由均衡",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-86",
    "title": "夔龙团纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["四合云纹", "夔龙纹", "寿字纹", "莲纹", "磬纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-夔龙团纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-夔龙团纹.png",
    "structure": "单独/自由对称",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-87",
    "title": "大雅斋花鸟纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["花卉纹", "鸟纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-大雅斋花鸟纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-大雅斋花鸟纹.png",
    "structure": "适合/均衡式",
  
    "structureL1": "单独纹样",
    "structureL2": "适合纹样",
  },
  {
    "id": "revival-88",
    "title": "宫灯云凤纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["凤纹", "宫灯纹", "云纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-宫灯云凤纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-宫灯云凤纹.png",
    "structure": "四方连续/错位散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-89",
    "title": "宫灯纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
"structure": "单独/自由式",
    "elements": ["宫灯纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-宫灯纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-宫灯纹.png",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-90",
    "title": "山水纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["山水纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-山水纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-山水纹.png",
    "structure": "单独/自由式",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-91",
    "title": "折枝花蝶纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["花卉纹", "蝴蝶纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-折枝花蝶纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-折枝花蝶纹.png",
    "structure": "四方连续/不规则散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-92",
    "title": "暗八仙纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
"structure": "四方连续/不规则散点",
    "elements": ["仙鹤纹", "云纹", "暗八仙纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-暗八仙纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-暗八仙纹.png",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-93",
    "title": "松鼠葡萄纹",
    "dynasty": "清代",
    "era": "",
    "culture": "在清代，松鼠葡萄纹是一种固定搭配，寓意多子多福。此外还搭配了蝴蝶、蜜蜂和云纹，更添自然之趣。",
    "elements": ["葡萄纹", "云纹", "松鼠纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-松鼠葡萄纹.webp",
    "nonCommercial": true,
    "thumbSrc": "/images/revival/thumbs/清代-松鼠葡萄纹.png",
    "structure": "四方连续/连缀式",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-94",
    "title": "果品蝠纹天华锦",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["蝙蝠纹", "果品纹", "锁子纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-果品蝠纹天华锦.webp",
    "thumbSrc": "/images/revival/thumbs/清代-果品蝠纹天华锦.png",
    "structure": "四方连续/重叠式",
  
    "structureL1": "四方连续",
    "structureL2": "重叠式",
  },
  {
    "id": "revival-95",
    "title": "海水江崖纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["海水江崖纹", "曲水纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-海水江崖纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-海水江崖纹.png",
    "structure": "单独/对称式",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-96",
    "title": "狮子纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["虎纹", "花卉纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-狮子纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-狮子纹.png",
    "structure": "四方连续/错位散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-97",
    "title": "球路双龙纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["双龙戏珠纹", "球路纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-球路双龙纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-球路双龙纹.png",
    "structure": "四方连续/几何连缀",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-98",
    "title": "皮球小团花",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["小团花"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-皮球小团花.webp",
    "thumbSrc": "/images/revival/thumbs/清代-皮球小团花.png",
    "structure": "单独/自由均衡散点式",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-99",
    "title": "石榴牡丹纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["石榴纹", "牡丹纹", "蝙蝠纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-石榴牡丹纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-石榴牡丹纹.png",
    "structure": "四方连续/不规则散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-100",
    "title": "缠枝八吉祥",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["八吉祥纹", "卷草纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-缠枝八吉祥.webp",
    "thumbSrc": "/images/revival/thumbs/清代-缠枝八吉祥.png",
    "structure": "四方连续/连缀式",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-101",
    "title": "缠枝八吉祥纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["八吉祥纹", "缠枝莲纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-缠枝八吉祥纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-缠枝八吉祥纹.png",
    "structure": "四方连续/连缀式",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-102",
    "title": "缠枝四季花纹",
    "dynasty": "清代",
    "era": "",
    "culture": "以牡丹、荷花、菊花、山茶花为四季之美。四季花纹也可看作是宋代一年景纹样的延伸，将一年中的花卉景色都尽收眼底。古人有不问四时的审美情趣，讲究意境的呈现，是中国古人独有的浪漫。",
    "elements": ["莲纹", "菊花纹", "牡丹纹", "梅花纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-缠枝四季花纹.webp",
    "nonCommercial": true,
    "thumbSrc": "/images/revival/thumbs/清代-缠枝四季花纹.png",
    "structure": "四方连续/缠绕连缀",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-103",
    "title": "缠枝牡丹纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["牡丹纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-缠枝牡丹纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-缠枝牡丹纹.png",
    "structure": "四方连续/连缀式",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-104",
    "title": "缠枝花果纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["莲纹", "牡丹纹", "石榴纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-缠枝花果纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-缠枝花果纹.png",
    "structure": "四方连续/连缀式",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-105",
    "title": "葫芦纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
"structure": "四方连续/缠绕式连缀",
    "elements": ["葫芦纹", "蝙蝠纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-葫芦纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-葫芦纹.png",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-106",
    "title": "蕉叶纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
"structure": "二方连续/直立式/散点式",
    "elements": ["蕉叶纹", "兽面纹", "云雷纹", "忍冬纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-蕉叶纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-蕉叶纹.png",
  
    "structureL1": "二方连续",
    "structureL2": "直立式",
  },
  {
    "id": "revival-107",
    "title": "蕉叶缠枝花纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["蕉叶纹", "海水纹", "缠枝纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-蕉叶缠枝花纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-蕉叶缠枝花纹.png",
    "structure": "二方连续/直立式/波线式",
  
    "structureL1": "二方连续",
    "structureL2": "直立式",
  },
  {
    "id": "revival-108",
    "title": "蝉纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
"structure": "二方连续/综合式",
    "elements": ["蝉纹", "兽面纹", "波曲纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-蝉纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-蝉纹.png",
  
    "structureL1": "二方连续",
    "structureL2": "综合式",
  },
  {
    "id": "revival-109",
    "title": "西番莲蝠纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
"structure": "单独/适合/角隅",
    "elements": ["蝙蝠纹", "西番莲纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-西番莲蝠纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-西番莲蝠纹.png",
  
    "structureL1": "单独纹样",
    "structureL2": "适合纹样",
  },
  {
    "id": "revival-110",
    "title": "金鱼纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["金鱼纹", "水草纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-金鱼纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-金鱼纹.png",
    "structure": "自由式",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-111",
    "title": "锦地团花",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["团花纹", "锦地纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-锦地团花.webp",
    "thumbSrc": "/images/revival/thumbs/清代-锦地团花.png",
    "structure": "四方连续/重叠式",
  
    "structureL1": "四方连续",
    "structureL2": "重叠式",
  },
  {
    "id": "revival-112",
    "title": "锦地开光花蝶纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["花蝶纹", "锦地纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-锦地开光花蝶纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-锦地开光花蝶纹.png",
    "structure": "单独/适合开光式",
  
    "structureL1": "单独纹样",
    "structureL2": "适合纹样",
  },
  {
    "id": "revival-113",
    "title": "鹤纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["缠枝纹", "四合如意纹", "仙鹤寿桃纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-鹤纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-鹤纹.png",
    "structure": "单独/角隅式   适合/开光式",
  
    "structureL1": "单独纹样",
    "structureL2": "适合纹样",
  },
  {
    "id": "revival-114",
    "title": "麒麟纹",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["麒麟纹", "花卉纹", "云纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-麒麟纹.webp",
    "thumbSrc": "/images/revival/thumbs/清代-麒麟纹.png",
    "structure": "单独/自由式",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-115",
    "title": "龙纹柿蒂窠",
    "dynasty": "清代",
    "era": "",
    "culture": "",
    "elements": ["龙纹", "云纹", "寿字纹", "四合云纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/清代-龙纹柿蒂窠.webp",
    "thumbSrc": "/images/revival/thumbs/清代-龙纹柿蒂窠.png",
    "structure": "单独/适合对称",
  
    "structureL1": "单独纹样",
    "structureL2": "适合纹样",
  },
  {
    "id": "revival-116",
    "title": "菱形天华锦（成都博物馆）",
    "dynasty": "现代",
    "era": "",
    "culture": "此纹样来自成都蜀锦博物馆。用丰富多样的小团花填充天华锦的骨架，在规整韵律的同时不失灵动俏皮。",
    "elements": ["小团花", "天华锦骨架"],
    "description": "",
    "detail": "",
    "src": "/images/revival/现代-菱形天华锦（成都博物馆）.webp",
    "nonCommercial": true,
    "thumbSrc": "/images/revival/thumbs/现代-菱形天华锦（成都博物馆）.png",
    "structure": "四方连续/几何连缀",
  
    "structureL1": "四方连续",
    "structureL2": "连缀式",
  },
  {
    "id": "revival-117",
    "title": "第319窟宝相花藻井",
    "dynasty": "盛唐",
    "era": "",
    "culture": "覆斗形藻井，是盛唐时期藻井艺术的典型范例，展现了盛唐时期追求丰满、华丽与秩序感的时代审美。宝相花层叠绚烂，颇具大唐气象。",
    "elements": ["宝相花"],
    "description": "",
    "detail": "",
    "src": "/images/revival/盛唐-第319窟宝相花藻井.webp",
    "nonCommercial": true,
    "thumbSrc": "/images/revival/thumbs/盛唐-第319窟宝相花藻井.png",
    "structure": "适合/离心式/角隅式",
  
    "structureL1": "单独纹样",
    "structureL2": "适合纹样",
  },
  {
    "id": "revival-118",
    "title": "波曲纹",
    "dynasty": "西周",
    "era": "",
    "culture": "",
"structure": "二方连续/波线式",
    "elements": ["波曲纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/西周-波曲纹.webp",
    "thumbSrc": "/images/revival/thumbs/西周-波曲纹.png",
  
    "structureL1": "二方连续",
    "structureL2": "波线式",
  },
  {
    "id": "revival-119",
    "title": "窃曲纹",
    "dynasty": "西周",
    "era": "",
    "culture": "",
"structure": "二方连续/散点式",
    "elements": ["窃曲纹", "波曲纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/西周-窃曲纹.webp",
    "thumbSrc": "/images/revival/thumbs/西周-窃曲纹.png",
  
    "structureL1": "二方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-120",
    "title": "第285窟莲花忍冬藻井",
    "dynasty": "西魏",
    "era": "",
    "culture": "藻井采用传统的「斗四方井套叠」结构，方框层叠，是藻井早期常用的结构形式。中心卷瓣大莲花象征佛国无染，有明显的异域风格，旁边辅以多种形态忍冬和火焰纹，角隅四朵莲花静静绽放。",
    "elements": ["忍冬纹", "莲花纹", "火焰纹"],
    "structure": "单独/适合/角隅",
    "description": "",
    "detail": "",
    "src": "/images/revival/西魏-第285窟莲花忍冬藻井.webp",
    "nonCommercial": true,
    "thumbSrc": "/images/revival/thumbs/西魏-第285窟莲花忍冬藻井.png",
    "structure": "团窠",
  
    "structureL1": "单独纹样",
    "structureL2": "适合纹样",
  },
  {
    "id": "revival-121",
    "title": "秋山鹿纹",
    "dynasty": "辽代",
    "era": "",
    "culture": "",
    "elements": ["秋山纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/辽代-秋山鹿纹.webp",
    "thumbSrc": "/images/revival/thumbs/辽代-秋山鹿纹.png",
    "structure": "四方连续/错位散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-122",
    "title": "鱼纹",
    "dynasty": "辽代",
    "era": "",
    "culture": "",
    "elements": [
      "鱼纹"
    ],
    "description": "",
    "detail": "",
    "src": "/images/revival/辽代-鱼纹.webp",
    "thumbSrc": "/images/revival/thumbs/辽代-鱼纹.png",
    "structure": "动物造型",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-123",
    "title": "双凤朝阳纹",
    "dynasty": "近代",
    "era": "",
    "culture": "",
    "elements": ["凤纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/近代-双凤朝阳纹.webp",
    "thumbSrc": "/images/revival/thumbs/近代-双凤朝阳纹.png",
    "structure": "单独/对称式",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",
  },
  {
    "id": "revival-124",
    "title": "春水滴珠窠",
    "dynasty": "金代",
    "era": "",
    "culture": "",
    "elements": ["大雁纹", "海东青纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/金代-春水滴珠窠.webp",
    "thumbSrc": "/images/revival/thumbs/金代-春水滴珠窠.png",
    "structure": "四方连续/错位散点",
  
    "structureL1": "四方连续",
    "structureL2": "散点式",
  },
  {
    "id": "revival-125",
    "title": "双头鸟纹",
    "dynasty": "魏晋南北朝",
    "era": "",
    "culture": "",
    "elements": ["鸟纹", "花纹"],
    "description": "",
    "detail": "",
    "src": "/images/revival/魏晋南北朝-双头鸟纹.webp",
    "thumbSrc": "/images/revival/thumbs/魏晋南北朝-双头鸟纹.png",
    "structure": "单独/自由对称",
  
    "structureL1": "单独纹样",
    "structureL2": "自由纹样",},
  {
    id: 'revival-126',
    title: '缠枝梅花纹',
    dynasty: '宋代',
    era: '',
    culture: '',
    elements: ['梅花纹', '缠枝纹'],
    description: '',
    detail: '',
    src: '/images/revival/宋代-缠枝梅花纹.webp',
    thumbSrc: '/images/revival/thumbs/宋代-缠枝梅花纹.png',
    structure: '四方连续/自由缠绕连缀',
    structureL1: '四方连续',
    structureL2: '连缀式',
    isNew: true,
  },
  {
    id: 'revival-127',
    title: '升仙三界图之天界',
    dynasty: '汉代',
    era: '',
    culture: '',
    elements: ['双龙', '金乌', '月亮', '太阳', '蟾蜍'],
    description: '',
    detail: '',
    src: '/images/revival/汉代-升仙三界图之天界.webp',
    thumbSrc: '/images/revival/thumbs/汉代-升仙三界图之天界.png',
    structure: '单独/自由',
    structureL1: '单独纹样',
    structureL2: '自由纹样',
    isNew: true,
  },
  {
    id: 'revival-128',
    title: '水波纹',
    dynasty: '清代',
    era: '',
    culture: '',
    elements: ['水波纹'],
    description: '',
    detail: '',
    src: '/images/revival/清代-水波纹.webp',
    thumbSrc: '/images/revival/thumbs/清代-水波纹.png',
    structure: '四方连续/几何连缀',
    structureL1: '四方连续',
    structureL2: '连缀式',
    isNew: true,
  },
  {
    id: 'revival-129',
    title: '亭台楼阁纹',
    dynasty: '现代',
    era: '',
    culture: '此纹样来自成都蜀锦博物馆，原名为巴蜀揽胜纹，以中国亭台楼阁为元素，搭配水景、树景等，将中式园林之美尽收眼底。',
    elements: ['亭台楼阁纹', '人物纹', '草木纹'],
    description: '',
    detail: '',
    src: '/images/revival/现代-亭台楼阁纹.webp',
    nonCommercial: true,
    thumbSrc: '/images/revival/thumbs/现代-亭台楼阁纹.png',
    structure: '四方连续/不规则散点',
    structureL1: '四方连续',
    structureL2: '散点式',
    isNew: true,
  },
  {
    id: 'revival-130',
    title: '春水荷塘双鹅纹',
    dynasty: '辽代',
    era: '',
    culture: '',
    elements: ['双鹅纹', '荷塘纹'],
    description: '',
    detail: '',
    src: '/images/revival/辽代-春水荷塘双鹅纹.webp',
    thumbSrc: '/images/revival/thumbs/辽代-春水荷塘双鹅纹.png',
    structure: '单独/自由',
    structureL1: '单独纹样',
    structureL2: '自由纹样',
    isNew: true,
  },
  {
    id: 'revival-131',
    title: '菱格雁蝶纹',
    dynasty: '辽代',
    era: '',
    culture: '简约抽象的大雁剪影四只成花，蝴蝶拥簇着中心的柿蒂花卉，菱格骨架做了婉曲的设计，让整体呈现自由野趣之感。大雁元素常被用在辽代纹样中，如海东青补雁纹等。',
    elements: ['雁纹', '蝶纹', '菱格'],
    description: '',
    detail: '',
    src: '/images/revival/辽代-菱格雁蝶纹.webp',
    nonCommercial: true,
    thumbSrc: '/images/revival/thumbs/辽代-菱格雁蝶纹.png',
    structure: '四方连续/几何连缀',
    structureL1: '四方连续',
    structureL2: '连缀式',
    isNew: true,
  },
  {
    id: 'revival-132',
    title: '复合菱纹',
    dynasty: '魏晋南北朝',
    era: '',
    culture: '菱形纹用卷云纹形成骨架，菱格之间用小团花连接，内填朱雀、狮子等纹样，是本土元素与外来元素的融合。',
    elements: ['菱纹', '狮子纹', '朱雀纹'],
    description: '',
    detail: '',
    src: '/images/revival/魏晋南北朝-复合菱纹.webp',
    nonCommercial: true,
    thumbSrc: '/images/revival/thumbs/魏晋南北朝-复合菱纹.png',
    structure: '四方连续/几何连缀',
    structureL1: '四方连续',
    structureL2: '连缀式',
    isNew: true,
  },
  {
    id: 'revival-133',
    title: '卐字地龙纹',
    dynasty: '元代',
    structure: '四方连续/重叠式',
    structureL1: '四方连续',
    structureL2: '重叠式',
    elements: ['卐字纹', '龙纹'],
    src: '/images/revival/元代-卐字地龙纹.webp',
    thumbSrc: '/images/revival/thumbs/元代-卐字地龙纹.png',
    isNew: true,
  },
  {
    id: 'revival-134',
    title: '柿蒂窠',
    dynasty: '元代',
    structure: '四方连续/重叠式',
    structureL1: '四方连续',
    structureL2: '重叠式',
    elements: ['柿蒂纹', '卷草纹'],
    culture: '柿蒂纹是中国经典纹样，因其形状与柿子的果蒂相似，故在唐代得名柿蒂纹。早在商周时期，就有四叶纹作为其原型。柿蒂纹是典型的十字型结构，也代表了中国古代四方向、春夏秋冬、金木水火等宇宙观。纹样的柿蒂纹中填入了花卉纹，也称柿蒂窠。',
    src: '/images/revival/元代-柿蒂窠.webp',
    nonCommercial: true,
    thumbSrc: '/images/revival/thumbs/元代-柿蒂窠.png',
    isNew: true,
  },
  {
    id: 'revival-135',
    title: '荷塘鸳鸯纹',
    dynasty: '元代',
    structure: '单独/适合',
    structureL1: '单独纹样',
    structureL2: '适合纹样',
    elements: ['满池娇纹'],
    src: '/images/revival/元代-荷塘鸳鸯纹.webp',
    thumbSrc: '/images/revival/thumbs/元代-荷塘鸳鸯纹.png',
    isNew: true,
  },
  {
    id: 'revival-136',
    title: '落花流水纹',
    dynasty: '元代',
    structure: '四方连续/重叠式',
    structureL1: '四方连续',
    structureL2: '重叠式',
    elements: ['云纹', '水波纹'],
    src: '/images/revival/元代-落花流水纹.webp',
    thumbSrc: '/images/revival/thumbs/元代-落花流水纹.png',
    isNew: true,
  },
  {
    id: 'revival-137',
    title: '鸳鸯纹',
    dynasty: '元代',
    structure: '四方连续/散点式',
    structureL1: '四方连续',
    structureL2: '散点式',
    elements: ['鸳鸯纹'],
    src: '/images/revival/元代-鸳鸯纹.webp',
    thumbSrc: '/images/revival/thumbs/元代-鸳鸯纹.png',
    isNew: true,
  },
];

// 自动生成: 元素分类体系
export const ELEMENT_CATEGORIES = [
  { cat: '动物', elements: ['龙纹','凤纹','麒麟纹','狮子纹','虎纹','鹿纹','鸟纹','鱼纹','鸳鸯纹','蝴蝶纹','蝙蝠纹','仙鹤纹','大雁纹','海东青纹','朱雀纹','鸷鸟纹','松鼠纹','蛙纹','蝉纹','蟾蜍纹','金鱼纹','蟠螭','蟠龙纹','夔龙纹','夔凤纹','双龙戏珠纹','变型鸟纹','变形鸟纹','团窠对鹿纹','太极鱼纹','对鸟团窠','摩羯纹','秋山纹','绵羊太子纹','联珠对马纹','鱼鳞纹','花蝶纹','仙鹤寿桃纹'] },
  { cat: '植物', elements: ['莲花纹','牡丹纹','忍冬纹','菊花纹','梅花纹','葡萄纹','石榴纹','莲花','忍冬','宝相花','缠枝纹','卷草纹','蕉叶纹','花卉纹','花纹','茶花纹','山茶花纹','柿蒂纹','葫芦纹','西番莲纹','折枝花纹','团花纹','小团花','小团花纹','小花纹','四季花纹','缠枝花纹','缠枝莲纹','石榴','联珠小团花','艾草纹','海石榴纹','十字折枝花纹','果品纹','水草纹','方形宝相花纹','方形小宝相纹'] },
  { cat: '人物', elements: ['飞天','羽人纹','和合二仙纹','日神纹'] },
  { cat: '几何', elements: ['云纹','如意纹','回型纹','方胜纹','锁子纹','曲水纹','菱纹','冰裂纹','旋涡纹','涡纹','波曲纹','龟背纹','十二纹','卐字纹','火焰纹','球路纹','连钱纹','窃曲纹','锦地纹','开光纹','四合云纹','四合如意纹','杯纹菱','云雷纹','联珠纹'] },
  { cat: '器物', elements: ['八吉祥纹','博古纹','杂宝纹','暗八仙纹','华盖','宫灯纹','磬纹','文字纹','寿字纹','天华锦骨架','葫芦灯纹'] },
  { cat: '其他', elements: ['怪兽纹','兽面纹','五毒纹','三多纹','传统纹样','玄武纹','山水纹','地纹','变型水纹','海水纹','海水江崖纹','纹样','纹','满池娇纹'] },
];
