// ==================== 素材分类维度 ====================

/** 朝代 */
export const DYNASTIES = [
  '商周', '春秋战国', '秦汉', '魏晋南北朝',
  '隋唐五代', '宋辽金', '元', '明', '清', '近现代',
] as const;

/** 具体朝代 → 大分类映射 */
export const DYNASTY_ALIASES: Record<string, string> = {
  '唐代': '隋唐五代',
  '战国': '春秋战国',
  '汉代': '秦汉',
  '明代': '明',
  '清代': '清',
  '辽代': '宋辽金',
  '金代': '宋辽金',
  '北凉': '魏晋南北朝',
};

/** 载体 */
export const CARRIERS = [
  '青铜器', '陶瓷', '漆器', '织物', '刺绣',
  '壁画', '石刻', '金银器', '玉器', '木器', '掐丝珐琅', '建筑', '其他',
] as const;

/** 结构 */
export const STRUCTURES = [
  '自由', '适合', '角隅', '二方连续', '四方连续', '组合', '开光',
] as const;

/** 颜色 */
export const COLORS = [
  '青蓝', '赤红', '黄金', '白素', '黑墨', '绿翠', '紫绀', '赭褐', '烟灰', '银素', '樱粉', '多色',
] as const;

/** 元素三级分类 */
export interface ElementNode {
  id: string;
  label: string;
  children?: ElementNode[];
}

export const ELEMENT_TREE: ElementNode[] = [
  {
    id: 'niaoshou', label: '鸟兽鱼虫纹', children: [
      { id: 'huwen', label: '虎纹' },
      { id: 'mawen', label: '马纹', children: [
        { id: 'lianzhuduima', label: '联珠对马纹' },
      ]},
      { id: 'tuwen', label: '兔纹' },
      { id: 'niao', label: '鸟纹', children: [
        { id: 'duiniaotuanqun', label: '对鸟团窠纹' },
        { id: 'haidongqing', label: '海东青捕大雁纹' },
      ]},
      { id: 'shizi', label: '狮子纹' },
      { id: 'chan', label: '蝉纹' },
      { id: 'yuwen', label: '鱼纹' },
      { id: 'wawen', label: '蛙纹' },
      { id: 'fuwen', label: '蝠纹' },
      { id: 'yuanyang', label: '鸳鸯纹', children: [
        { id: 'yuanyangtuanqun', label: '鸳鸯团窠纹' },
      ]},
      { id: 'hudie', label: '蝴蝶纹' },
      { id: 'tuanqunlu', label: '团窠鹿纹' },
    ],
  },
  {
    id: 'zhiwu', label: '植物纹', children: [
      { id: 'jiaoye', label: '蕉叶纹' },
      { id: 'xifanlian', label: '西番莲' },
      { id: 'mudan', label: '牡丹纹' },
      { id: 'sijihua', label: '四季花纹' },
      { id: 'chanzhi', label: '缠枝纹' },
      { id: 'juancao', label: '卷草纹' },
      { id: 'hulu', label: '葫芦纹' },
      { id: 'meihua', label: '梅花纹' },
      { id: 'lian', label: '莲纹' },
      { id: 'shiliu', label: '石榴纹' },
      { id: 'haishiliu', label: '海石榴纹' },
      { id: 'huahui', label: '花卉纹' },
      { id: 'mudanlian', label: '牡丹莲纹' },
      { id: 'goulian', label: '勾莲纹' },
    ],
  },
  {
    id: 'jixiang', label: '吉祥纹', children: [
      { id: 'sanduo', label: '三多纹' },
      { id: 'fulushouxi', label: '福禄寿喜纹' },
      { id: 'helutongchun', label: '鹤鹿同春' },
      { id: 'lianshengshengyuan', label: '连升三元' },
      { id: 'jiqingyouyu', label: '吉庆有余' },
      { id: 'wufupengshou', label: '五福捧寿' },
      { id: 'qilinsongzi', label: '麒麟送子' },
      { id: 'sanduojiuru', label: '三多九如' },
      { id: 'huzhenwudu', label: '虎镇五毒' },
      { id: 'liuhetongchun', label: '六和同春' },
      { id: 'niannianyouyu', label: '年年有余' },
      { id: 'longfengchengxiang', label: '龙凤呈祥' },
      { id: 'fengximudan', label: '凤戏牡丹' },
      { id: 'mashangfenghou', label: '马上封侯' },
      { id: 'xishangmeishao', label: '喜上眉梢' },
      { id: 'songheyanian', label: '松鹤延年' },
      { id: 'heqijixiang', label: '和气吉祥' },
      { id: 'shizigunxiuqiu', label: '狮子滚绣球' },
    ],
  },
  {
    id: 'jihe', label: '几何纹', children: [
      { id: 'qiulu', label: '球路锦纹', children: [
        { id: 'q4banhua', label: '四瓣花式簇四球路' },
        { id: 'q4huan', label: '环式簇四球路' },
        { id: 'q6chong', label: '簇六重球纹' },
        { id: 'q6tianhua', label: '簇六填花纹' },
        { id: 'q6chechuan', label: '簇六车钏球路纹' },
        { id: 'q4tiaobai', label: '簇四挑白球路纹' },
        { id: 'q4xie', label: '簇四斜球纹' },
        { id: 'qianqian', label: '连钱纹' },
      ]},
      { id: 'qushui', label: '曲水纹' },
      { id: 'lingwen', label: '菱纹' },
      { id: 'lianzhu', label: '联珠纹' },
      { id: 'guibei', label: '龟背纹' },
      { id: 'sidayun', label: '四达晕' },
      { id: 'liudayun', label: '六达晕' },
      { id: 'badayun', label: '八达晕' },
      { id: 'tianhuajin', label: '天华锦纹' },
    ],
  },
  {
    id: 'wenzi', label: '文字纹', children: [
      { id: 'shouzi', label: '寿字纹' },
      { id: 'fuzi', label: '福字纹' },
      { id: 'wanzi', label: '万字纹' },
      { id: 'xizi', label: '喜字纹' },
    ],
  },
  {
    id: 'ziran', label: '自然纹', children: [
      { id: 'yun', label: '云纹', children: [
        { id: 'yunlei', label: '云雷纹' },
        { id: 'sanjiao', label: '三角云纹' },
        { id: 'yunqi', label: '云气纹' },
        { id: 'juanyun', label: '卷云纹' },
        { id: 'duoyun', label: '朵云纹' },
        { id: 'huoyanyun', label: '火焰云纹' },
        { id: 'siheyun', label: '四合云纹' },
        { id: 'dieyun', label: '叠云纹' },
        { id: 'yulin', label: '鱼鳞云纹' },
        { id: 'tuanyun', label: '团云纹' },
        { id: 'ruyisihe', label: '如意四合云纹' },
        { id: 'ruyiwen', label: '如意纹' },
      ]},
      { id: 'shui', label: '水纹', children: [
        { id: 'haishuijiangya', label: '海水江崖纹' },
        { id: 'shuibo', label: '水波纹' },
        { id: 'hailang', label: '海浪水纹' },
      ]},
      { id: 'huo', label: '火纹', children: [
        { id: 'wowen', label: '涡纹' },
        { id: 'beiguang', label: '背光火焰纹' },
        { id: 'shanxing', label: '山形火焰纹' },
        { id: 'huoyanlongzhu', label: '火焰龙珠纹' },
      ]},
    ],
  },
  {
    id: 'shenshou', label: '神兽纹', children: [
      { id: 'chi', label: '螭纹' },
      { id: 'shoumian', label: '兽面纹' },
      { id: 'long', label: '龙纹', children: [
        { id: 'zhenglong', label: '正龙纹' },
      ]},
      { id: 'feng', label: '凤纹' },
      { id: 'qilin', label: '麒麟纹' },
      { id: 'sishen', label: '四神纹' },
      { id: 'mojie', label: '摩羯纹' },
    ],
  },
  {
    id: 'yixiang', label: '意象纹样', children: [
      { id: 'baoxianghua', label: '宝相花' },
      { id: 'tuanhua', label: '团花' },
    ],
  },
  {
    id: 'renwu', label: '人物纹', children: [
      { id: 'hehe', label: '和合二仙' },
      { id: 'magu', label: '麻姑献寿' },
      { id: 'feitian', label: '飞天纹' },
      { id: 'jiuyang', label: '九阳消寒' },
      { id: 'mianyang', label: '绵羊太子' },
      { id: 'liuhai', label: '刘海戏金蟾' },
      { id: 'baizi', label: '百子婴戏' },
    ],
  },
  {
    id: 'qiwu', label: '器物纹', children: [
      { id: 'deng', label: '灯纹' },
      { id: 'bogu', label: '博古纹' },
      { id: 'anbaxian', label: '暗八仙纹' },
      { id: 'zabao', label: '杂宝纹' },
    ],
  },
  {
    id: 'zongjiao', label: '宗教纹样', children: [
      { id: 'fobabao', label: '佛八宝纹' },
      { id: 'anbaxian2', label: '暗八仙纹' },
    ],
  },
  {
    id: 'changjing', label: '场景纹', children: [
      { id: 'chunshui', label: '春水秋山纹' },
      { id: 'shanshui', label: '山水纹' },
      { id: 'manchijiao', label: '满池娇纹' },
    ],
  },
];

// ==================== 素材数据 ====================

export interface MaterialItem {
  id: string;
  title: string;
  dynasty: string;        // 朝代
  carrier: string;        // 载体
  elements: string[];     // 元素 ID（可多个，含二/三级）
  structure: string;      // 结构
  colors: string[];       // 颜色
  description: string;    // 描述
  src: string;            // 图片路径
  isNew?: boolean;
}

/** 占位素材（待补充真实数据） */
const materials: MaterialItem[] = [
  {
    id: 'mat-mr61j6ve-oji',
    title: '飞天纹',
    dynasty: '北凉',
    carrier: '壁画',
    elements: ["feitian"],
    structure: '单独',
    colors: ["多色"],
    description: '北凉壁画，飞天纹，单独排布，多色配色',
    src: '/images/materials/北凉-壁画-飞天纹-单独-多色.png',
  },
  {
    id: 'mat-mr61j6wv-qr0',
    title: '朵型宝相花',
    dynasty: '唐代',
    carrier: '壁画',
    elements: ["baoxianghua"],
    structure: '适合',
    colors: ["多色"],
    description: '唐代壁画，朵型宝相花，适合排布，多色配色',
    src: '/images/materials/唐代-壁画-朵型宝相花-适合-多色.png',
  },
  {
    id: 'mat-mr61j6y5-kq1',
    title: '对鸟团窠',
    dynasty: '唐代',
    carrier: '漆器',
    elements: ["duiniaotuanqun"],
    structure: '四方连续',
    colors: ["绿翠"],
    description: '唐代漆器，对鸟团窠，四方连续排布，绿翠配色',
    src: '/images/materials/唐代-漆器-对鸟团窠-四方连续-绿翠.png',
  },
  {
    id: 'mat-mr61j6yw-nz7',
    title: '团花纹',
    dynasty: '唐代',
    carrier: '织物',
    elements: ["tuanhua"],
    structure: '四方连续',
    colors: ["赤红"],
    description: '唐代织物，团花纹，四方连续排布，赤红配色',
    src: '/images/materials/唐代-织物-团花纹-四方连续-赤红.png',
  },
  {
    id: 'mat-mr61j6z8-6wy',
    title: '团花纹',
    dynasty: '唐代',
    carrier: '织物',
    elements: ["tuanhua"],
    structure: '四方连续',
    colors: ["赭褐"],
    description: '唐代织物，团花纹，四方连续排布，赭褐配色',
    src: '/images/materials/唐代-织物-团花纹-四方连续-赭褐.png',
  },
  {
    id: 'mat-mr61j70j-zo9',
    title: '小宝相纹',
    dynasty: '唐代',
    carrier: '织物',
    elements: ["baoxianghua"],
    structure: '四方连续',
    colors: ["赭褐"],
    description: '唐代织物，小宝相纹，四方连续排布，赭褐配色',
    src: '/images/materials/唐代-织物-小宝相纹-四方连续-赭褐.png',
  },
  {
    id: 'mat-mr61j71a-cho',
    title: '方形小宝相',
    dynasty: '唐代',
    carrier: '织物',
    elements: ["baoxianghua"],
    structure: '四方连续',
    colors: ["赭褐"],
    description: '唐代织物，方形小宝相，四方连续排布，赭褐配色',
    src: '/images/materials/唐代-织物-方形小宝相-四方连续-赭褐.png',
  },
  {
    id: 'mat-mr61j72a-nmq',
    title: '方形小宝相纹',
    dynasty: '唐代',
    carrier: '织物',
    elements: ["baoxianghua"],
    structure: '四方连续',
    colors: ["绿翠"],
    description: '唐代织物，方形小宝相纹，四方连续排布，绿翠配色',
    src: '/images/materials/唐代-织物-方形小宝相纹-四方连续-绿翠.png',
  },
  {
    id: 'mat-mr61j73l-w3x',
    title: '联珠对马纹',
    dynasty: '唐代',
    carrier: '织物',
    elements: ["lianzhuduima"],
    structure: '四方连续',
    colors: ["黄金"],
    description: '唐代织物，联珠对马纹，四方连续排布，黄金配色',
    src: '/images/materials/唐代-织物-联珠对马纹-四方连续-黄金.png',
  },
  {
    id: 'mat-mr61j741-yjp',
    title: '六出团花纹',
    dynasty: '唐代',
    carrier: '金银器',
    elements: ["tuanhua"],
    structure: '适合',
    colors: ["赭褐"],
    description: '唐代金银器，六出团花纹，适合排布，赭褐配色',
    src: '/images/materials/唐代-金银器-六出团花纹-适合-赭褐.png',
  },
  {
    id: 'mat-mr61j754-7xh',
    title: '团窠鹿纹',
    dynasty: '唐代',
    carrier: '金银器',
    elements: ["tuanqunlu"],
    structure: '适合',
    colors: ["黄金"],
    description: '唐代金银器，团窠鹿纹，适合排布，黄金配色',
    src: '/images/materials/唐代-金银器-团窠鹿纹-适合-黄金.png',
  },
  {
    id: 'mat-mr61j76m-0xt',
    title: '摩羯纹',
    dynasty: '唐代',
    carrier: '金银器',
    elements: ["mojie"],
    structure: '适合',
    colors: ["黄金"],
    description: '唐代金银器，摩羯纹，适合排布，黄金配色',
    src: '/images/materials/唐代-金银器-摩羯纹-适合-黄金.png',
  },
  {
    id: 'mat-mr61j77c-hf8',
    title: '狮子纹',
    dynasty: '唐代',
    carrier: '金银器',
    elements: ["shizi"],
    structure: '适合',
    colors: ["黄金"],
    description: '唐代金银器，狮子纹，适合排布，黄金配色',
    src: '/images/materials/唐代-金银器-狮子纹-适合-黄金.png',
  },
  {
    id: 'mat-mr61j793-yd3',
    title: '鸳鸯团窠纹',
    dynasty: '唐代',
    carrier: '金银器',
    elements: ["yuanyangtuanqun"],
    structure: '适合',
    colors: ["黄金"],
    description: '唐代金银器，鸳鸯团窠纹，适合排布，黄金配色',
    src: '/images/materials/唐代-金银器-鸳鸯团窠纹-适合-黄金.png',
  },
  {
    id: 'mat-mr61j79n-zqx',
    title: '三角云纹',
    dynasty: '战国',
    carrier: '青铜器',
    elements: ["sanjiao"],
    structure: '二方连续',
    colors: ["绿翠"],
    description: '战国青铜器，三角云纹，二方连续排布，绿翠配色',
    src: '/images/materials/战国-青铜器-三角云纹-二方连续-绿翠.png',
  },
  {
    id: 'mat-mr61j7a9-v8h',
    title: '卷云纹',
    dynasty: '战国',
    carrier: '青铜器',
    elements: ["juanyun"],
    structure: '二方连续',
    colors: ["绿翠"],
    description: '战国青铜器，卷云纹，二方连续排布，绿翠配色',
    src: '/images/materials/战国-青铜器-卷云纹-二方连续-绿翠.png',
  },
  {
    id: 'mat-mr61j7bd-xci',
    title: '团云',
    dynasty: '明代',
    carrier: '其他',
    elements: ["tuanyun"],
    structure: '自由',
    colors: ["多色"],
    description: '明代其他，团云，自由排布，多色配色',
    src: '/images/materials/明代-水陆画-团云-自由-多色.png',
  },
  {
    id: 'mat-mr61j7cq-elq',
    title: '火焰云纹',
    dynasty: '明代',
    carrier: '其他',
    elements: ["huoyanyun"],
    structure: '自由',
    colors: ["黄金"],
    description: '明代其他，火焰云纹，自由排布，黄金配色',
    src: '/images/materials/明代-水陆画-火焰云纹-自由-黄金.png',
  },
  {
    id: 'mat-mr61j7dr-tz7',
    title: '变型云雷纹',
    dynasty: '明代',
    carrier: '织物',
    elements: ["yunlei"],
    structure: '四方连续',
    colors: ["黄金"],
    description: '明代织物，变型云雷纹，四方连续排布，黄金配色',
    src: '/images/materials/明代-织物-变型云雷纹-四方连续-黄金.png',
  },
  {
    id: 'mat-mr61j7e9-f87',
    title: '变形四合云纹',
    dynasty: '明代',
    carrier: '织物',
    elements: ["siheyun"],
    structure: '四方连续',
    colors: ["黄金"],
    description: '明代织物，变形四合云纹，四方连续排布，黄金配色',
    src: '/images/materials/明代-织物-变形四合云纹-四方连续-黄金.png',
  },
  {
    id: 'mat-mr61j7f2-t5q',
    title: '团云纹',
    dynasty: '明代',
    carrier: '织物',
    elements: ["tuanyun"],
    structure: '四方连续',
    colors: ["黄金"],
    description: '明代织物，团云纹，四方连续排布，黄金配色',
    src: '/images/materials/明代-织物-团云纹-四方连续-黄金.png',
  },
  {
    id: 'mat-mr61j7fk-lr0',
    title: '杂宝团纹',
    dynasty: '明代',
    carrier: '织物',
    elements: ["zabao"],
    structure: '四方连续',
    colors: ["绿翠"],
    description: '明代织物，杂宝团纹，四方连续排布，绿翠配色',
    src: '/images/materials/明代-织物-杂宝团纹-四方连续-绿翠.png',
  },
  {
    id: 'mat-mr61j7g0-5pa',
    title: '杂宝团花纹',
    dynasty: '明代',
    carrier: '织物',
    elements: ["zabao"],
    structure: '四方连续',
    colors: ["绿翠"],
    description: '明代织物，杂宝团花纹，四方连续排布，绿翠配色',
    src: '/images/materials/明代-织物-杂宝团花纹-四方连续-绿翠.png',
  },
  {
    id: 'mat-mr61j7gp-ya3',
    title: '如意四合云纹',
    dynasty: '明代',
    carrier: '陶瓷',
    elements: ["ruyisihe"],
    structure: '自由',
    colors: ["多色"],
    description: '明代陶瓷，如意四合云纹，自由排布，多色配色',
    src: '/images/materials/明代-陶瓷-如意四合云纹-自由-多色.png',
  },
  {
    id: 'mat-mr61j7hh-o1u',
    title: '四合如意云纹',
    dynasty: '明',
    carrier: '织物',
    elements: ["ruyisihe"],
    structure: '四方连续',
    colors: ["青蓝"],
    description: '明织物，四合如意云纹，四方连续排布，青蓝配色',
    src: '/images/materials/明清-织物-四合如意云纹-四方连续-青蓝.png',
  },
  {
    id: 'mat-mr61j7i1-g73',
    title: '变形如意云纹',
    dynasty: '清代',
    carrier: '木器',
    elements: ["ruyiwen"],
    structure: '自由',
    colors: ["赭褐"],
    description: '清代木器，变形如意云纹，自由排布，赭褐配色',
    src: '/images/materials/清代-家具装饰-变形如意云纹-自由-赭褐.png',
  },
  {
    id: 'mat-mr61j7iz-685',
    title: '宝相花纹',
    dynasty: '清代',
    carrier: '掐丝珐琅',
    elements: ["baoxianghua"],
    structure: '适合',
    colors: ["多色"],
    description: '清代掐丝珐琅，宝相花纹，适合排布，多色配色',
    src: '/images/materials/清代-掐丝珐琅-宝相花纹-适合-多色.png',
  },
  {
    id: 'mat-mr61j7jb-qqz',
    title: '鱼鳞云纹',
    dynasty: '清代',
    carrier: '掐丝珐琅',
    elements: ["yulin"],
    structure: '四方连续',
    colors: ["青蓝"],
    description: '清代掐丝珐琅，鱼鳞云纹，四方连续排布，青蓝配色',
    src: '/images/materials/清代-掐丝珐琅-鱼鳞云纹-四方连续-青蓝.png',
  },
  {
    id: 'mat-mr61j7k0-1xw',
    title: '卷云纹',
    dynasty: '清代',
    carrier: '木器',
    elements: ["juanyun"],
    structure: '四方连续',
    colors: ["赤红"],
    description: '清代木器，卷云纹，四方连续排布，赤红配色',
    src: '/images/materials/清代-木器-卷云纹-四方连续-赤红.png',
  },
  {
    id: 'mat-mr61j7lb-t4j',
    title: '蝠纹',
    dynasty: '清代',
    carrier: '木器',
    elements: ["fuwen"],
    structure: '适合',
    colors: ["赤红"],
    description: '清代木器，蝠纹，适合排布，赤红配色',
    src: '/images/materials/清代-木器-蝠纹-适合-赤红.png',
  },
  {
    id: 'mat-mr61j7lo-uw0',
    title: '变型卷云纹',
    dynasty: '清代',
    carrier: '木器',
    elements: ["juanyun"],
    structure: '四方连续',
    colors: ["绿翠"],
    description: '清代木器，变型卷云纹，四方连续排布，绿翠配色',
    src: '/images/materials/清代-竹盒装饰-变型卷云纹-四方连续-绿翠.png',
  },
  {
    id: 'mat-mr61j7mj-waw',
    title: '三多佛手柑纹',
    dynasty: '清代',
    carrier: '织物',
    elements: ["sanduo"],
    structure: '四方连续',
    colors: ["多色"],
    description: '清代织物，三多佛手柑纹，四方连续排布，多色配色',
    src: '/images/materials/清代-织物-三多佛手柑纹-四方连续-多色.png',
  },
  {
    id: 'mat-mr61j7nx-o9a',
    title: '三多石榴纹',
    dynasty: '清代',
    carrier: '织物',
    elements: ["sanduo"],
    structure: '四方连续',
    colors: ["多色"],
    description: '清代织物，三多石榴纹，四方连续排布，多色配色',
    src: '/images/materials/清代-织物-三多石榴纹-四方连续-多色.png',
  },
  {
    id: 'mat-mr61j7ov-028',
    title: '三多纹',
    dynasty: '清代',
    carrier: '织物',
    elements: ["sanduo"],
    structure: '福寿纹',
    colors: ["四方连续"],
    description: '清代织物，三多纹，福寿纹排布，四方连续配色',
    src: '/images/materials/清代-织物-三多纹-福寿纹-四方连续-多色.png',
  },
  {
    id: 'mat-mr61j7pm-x6n',
    title: '八角宫灯纹',
    dynasty: '清代',
    carrier: '织物',
    elements: ["deng"],
    structure: '自由',
    colors: ["多色"],
    description: '清代织物，八角宫灯纹，自由排布，多色配色',
    src: '/images/materials/清代-织物-八角宫灯纹-自由-多色.png',
  },
  {
    id: 'mat-mr61j7qj-t3r',
    title: '如意云纹',
    dynasty: '清代',
    carrier: '织物',
    elements: ["ruyiwen"],
    structure: '自由',
    colors: ["多色"],
    description: '清代织物，如意云纹，自由排布，多色配色',
    src: '/images/materials/清代-织物-如意云纹-自由-多色.png',
  },
  {
    id: 'mat-mr61j7rf-l6q',
    title: '宫灯纹',
    dynasty: '清代',
    carrier: '织物',
    elements: ["deng"],
    structure: '自由',
    colors: ["多色"],
    description: '清代织物，宫灯纹，自由排布，多色配色',
    src: '/images/materials/清代-织物-宫灯纹-自由-多色.png',
  },
  {
    id: 'mat-mr61j7t1-zdh',
    title: '正龙纹',
    dynasty: '清代',
    carrier: '织物',
    elements: ["zhenglong"],
    structure: '适合',
    colors: ["黄金"],
    description: '清代织物，正龙纹，适合排布，黄金配色',
    src: '/images/materials/清代-织物-正龙纹-适合-黄金.png',
  },
  {
    id: 'mat-mr61j7tq-sxr',
    title: '牡丹纹',
    dynasty: '清代',
    carrier: '织物',
    elements: ["mudan"],
    structure: '四方连续',
    colors: ["赤红"],
    description: '清代织物，牡丹纹，四方连续排布，赤红配色',
    src: '/images/materials/清代-织物-牡丹纹-四方连续-赤红.png',
  },
  {
    id: 'mat-mr61j7um-bzi',
    title: '狮子纹',
    dynasty: '清代',
    carrier: '织物',
    elements: ["shizi"],
    structure: '适合',
    colors: ["青蓝"],
    description: '清代织物，狮子纹，适合排布，青蓝配色',
    src: '/images/materials/清代-织物-狮子纹-适合-青蓝.png',
  },
  {
    id: 'mat-mr61j7v0-wgk',
    title: '叠云纹',
    dynasty: '清代',
    carrier: '陶瓷',
    elements: ["dieyun"],
    structure: '自由',
    colors: ["绿翠"],
    description: '清代陶瓷，叠云纹，自由排布，绿翠配色',
    src: '/images/materials/清代-陶瓷-叠云纹-自由-绿翠.png',
  },
  {
    id: 'mat-mr61j7vl-mhq',
    title: '圈圈团云纹',
    dynasty: '清代',
    carrier: '陶瓷',
    elements: ["tuanyun"],
    structure: '自由',
    colors: ["青蓝"],
    description: '清代陶瓷，圈圈团云纹，自由排布，青蓝配色',
    src: '/images/materials/清代-陶瓷-圈圈团云纹-自由-青蓝.png',
  },
  {
    id: 'mat-mr61j7x2-2ig',
    title: '牡丹纹',
    dynasty: '清代',
    carrier: '陶瓷',
    elements: ["mudan"],
    structure: '开光',
    colors: ["多色"],
    description: '清代陶瓷，牡丹纹，开光排布，多色配色',
    src: '/images/materials/清代-陶瓷-牡丹纹-开光-多色.png',
  },
  {
    id: 'mat-mr61j7xm-y5y',
    title: '云气纹',
    dynasty: '秦汉',
    carrier: '漆器',
    elements: ["yunqi"],
    structure: '适合',
    colors: ["黑墨"],
    description: '秦汉漆器，云气纹，适合排布，黑墨 配色',
    src: '/images/materials/秦汉-漆器-云气纹-适合-黑墨-(1).png',
  },
  {
    id: 'mat-mr61j7xz-60u',
    title: '云气纹',
    dynasty: '秦汉',
    carrier: '漆器',
    elements: ["yunqi"],
    structure: '适合',
    colors: ["黑墨"],
    description: '秦汉漆器，云气纹，适合排布，黑墨 配色',
    src: '/images/materials/秦汉-漆器-云气纹-适合-黑墨-(2).png',
  },
  {
    id: 'mat-mr61j7z4-nrm',
    title: '云气纹',
    dynasty: '秦汉',
    carrier: '漆器',
    elements: ["yunqi"],
    structure: '适合',
    colors: ["黑墨"],
    description: '秦汉漆器，云气纹，适合排布，黑墨 配色',
    src: '/images/materials/秦汉-漆器-云气纹-适合-黑墨-(3).png',
  },
  {
    id: 'mat-mr61j7zr-gur',
    title: '团花纹',
    dynasty: '辽代',
    carrier: '织物',
    elements: ["tuanhua"],
    structure: '四方连续',
    colors: ["赤红"],
    description: '辽代织物，团花纹，四方连续排布，赤红配色',
    src: '/images/materials/辽代-织物-团花纹-四方连续-赤红.png',
  },
  {
    id: 'mat-mr61j806-gaq',
    title: '宝相花纹',
    dynasty: '辽代',
    carrier: '织物',
    elements: ["baoxianghua"],
    structure: '四方连续',
    colors: ["赤红"],
    description: '辽代织物，宝相花纹，四方连续排布，赤红配色',
    src: '/images/materials/辽代-织物-宝相花纹-四方连续-赤红.png',
  },
  {
    id: 'mat-mr61j80m-jwj',
    title: '海东青捕大雁纹',
    dynasty: '金代',
    carrier: '织物',
    elements: ["haidongqing"],
    structure: '四方连续',
    colors: ["黄金"],
    description: '金代织物，海东青捕大雁纹，四方连续排布，黄金配色',
    src: '/images/materials/金代-织物-海东青捕大雁纹-四方连续-黄金.png',
  },
  {
    id: 'mat-mr6fzz19-s50',
    title: '方形小宝相纹',
    dynasty: '唐代',
    carrier: '壁画',
    elements: ["baoxianghua"],
    structure: '四方连续',
    colors: ["多色"],
    description: '唐代壁画，方形小宝相纹，四方连续排布，多色配色',
    src: '/images/materials/唐代-壁画-方形小宝相纹-四方连续-多色.png',
  },
  {
    id: 'mat-mr6fzz19-s51',
    title: '方形小宝相纹',
    dynasty: '唐代',
    carrier: '壁画',
    elements: ["baoxianghua"],
    structure: '四方连续',
    colors: ["赭褐"],
    description: '唐代壁画，方形小宝相纹，四方连续排布，赭褐配色',
    src: '/images/materials/唐代-壁画-方形小宝相纹-四方连续-赭褐.png',
  },
  {
    id: 'mat-mr6fzz19-s52',
    title: '牡丹纹',
    dynasty: '唐代',
    carrier: '壁画',
    elements: ["mudan"],
    structure: '自由',
    colors: ["多色"],
    description: '唐代壁画，牡丹纹，自由排布，多色配色',
    src: '/images/materials/唐代-壁画-牡丹纹-自由-多色-(2).png',
  },
  {
    id: 'mat-mr6fzz19-s53',
    title: '牡丹纹',
    dynasty: '唐代',
    carrier: '壁画',
    elements: ["mudan"],
    structure: '自由',
    colors: ["多色"],
    description: '唐代壁画，牡丹纹，自由排布，多色配色',
    src: '/images/materials/唐代-壁画-牡丹纹-自由-多色.png',
  },
  {
    id: 'mat-mr6fzz19-s54',
    title: '牡丹莲纹',
    dynasty: '唐代',
    carrier: '方砖',
    elements: ["mudanlian"],
    structure: '组合',
    colors: ["赭褐"],
    description: '唐代方砖，牡丹莲纹，组合排布，赭褐配色',
    src: '/images/materials/唐代-方砖-牡丹莲纹-组合-赭褐.png',
  },
  {
    id: 'mat-mr6fzz19-s55',
    title: '牡丹纹',
    dynasty: '唐代',
    carrier: '金银器',
    elements: ["mudan"],
    structure: '适合',
    colors: ["青蓝"],
    description: '唐代金银器，牡丹纹，适合排布，青蓝配色',
    src: '/images/materials/唐代-金银器-牡丹纹-适合-青蓝.png',
  },
  {
    id: 'mat-mr6fzz19-s56',
    title: '牡丹纹',
    dynasty: '宋代',
    carrier: '壁画',
    elements: ["mudan"],
    structure: '自由',
    colors: ["樱粉"],
    description: '宋代壁画，牡丹纹，自由排布，樱粉配色',
    src: '/images/materials/宋代-壁画-牡丹纹-自由-樱粉.png',
  },
  {
    id: 'mat-mr6fzz19-s57',
    title: '石榴纹',
    dynasty: '宋代',
    carrier: '壁画',
    elements: ["shiliu"],
    structure: '自由',
    colors: ["赤红"],
    description: '宋代壁画，石榴纹，自由排布，赤红配色',
    src: '/images/materials/宋代-壁画-石榴纹-自由-赤红.png',
  },
  {
    id: 'mat-mr6fzz19-s58',
    title: '麒麟纹',
    dynasty: '宋代',
    carrier: '画本',
    elements: ["qilin"],
    structure: '自由',
    colors: ["多色"],
    description: '宋代画本，麒麟纹，自由排布，多色配色',
    src: '/images/materials/宋代-画本-麒麟-自由-多色.png',
  },
  {
    id: 'mat-mr6fzz19-s59',
    title: '麒麟纹',
    dynasty: '战国',
    carrier: '织物',
    elements: ["qilin"],
    structure: '四方连续',
    colors: ["多色"],
    description: '战国织物，麒麟纹，四方连续排布，多色配色',
    src: '/images/materials/战国-织物-麒麟-四方连续-多色.png',
  },
  {
    id: 'mat-mr6fzz19-s5a',
    title: '牡丹纹',
    dynasty: '明代',
    carrier: '织物',
    elements: ["mudan"],
    structure: '四方连续',
    colors: ["多色"],
    description: '明代织物，牡丹纹，四方连续排布，多色配色',
    src: '/images/materials/明代-织物-牡丹纹-四方连续-多色.png',
  },
  {
    id: 'mat-mr6fzz19-s5b',
    title: '麒麟纹',
    dynasty: '汉代',
    carrier: '画像砖',
    elements: ["qilin"],
    structure: '自由',
    colors: ["赭褐"],
    description: '汉代画像砖，麒麟纹，自由排布，赭褐配色',
    src: '/images/materials/汉代-画像砖-麒麟纹-自由-赭褐.png',
  },
  {
    id: 'mat-mr6fzz19-s5c',
    title: '麒麟纹',
    dynasty: '汉代',
    carrier: '织物',
    elements: ["qilin"],
    structure: '四方连续',
    colors: ["赭褐"],
    description: '汉代织物，麒麟纹，四方连续排布，赭褐配色',
    src: '/images/materials/汉代-织物-麒麟纹-四方连续-赭褐.png',
  },
  {
    id: 'mat-mr6fzz19-s5d',
    title: '勾莲纹',
    dynasty: '清代',
    carrier: '木器',
    elements: ["goulian"],
    structure: '适合',
    colors: ["赭褐"],
    description: '清代木器，勾莲纹，适合排布，赭褐配色',
    src: '/images/materials/清代-木器-勾莲纹-适合-赭褐.png',
  },
  {
    id: 'mat-mr6fzz19-s5e',
    title: '卷草纹',
    dynasty: '清代',
    carrier: '陶瓷',
    elements: ["juancao"],
    structure: '自由',
    colors: ["绿翠"],
    description: '清代陶瓷，卷草纹，自由排布，绿翠配色',
    src: '/images/materials/清代-陶瓷-卷草纹-自由-绿翠.png',
  },
  {
    id: 'mat-mr6fzz19-s5f',
    title: '牡丹纹',
    dynasty: '清代',
    carrier: '陶瓷',
    elements: ["mudan"],
    structure: '自由',
    colors: ["青蓝"],
    description: '清代陶瓷，牡丹纹，自由排布，青蓝配色',
    src: '/images/materials/清代-陶瓷-牡丹纹-自由-青蓝.png',
  },
  {
    id: 'mat-mr6fzz19-s60',
    title: '麒麟纹',
    dynasty: '清代',
    carrier: '陶瓷',
    elements: ["qilin"],
    structure: '自由',
    colors: ["青蓝"],
    description: '清代陶瓷，麒麟纹，自由排布，青蓝配色',
    src: '/images/materials/清代-陶瓷-麒麟-自由-青蓝.png',
  },
];

export default materials;

/** 展开元素树为扁平 ID→label 映射 */
export function flattenElements(tree: ElementNode[]): Map<string, string> {
  const map = new Map<string, string>();
  function walk(nodes: ElementNode[]) {
    for (const n of nodes) {
      map.set(n.id, n.label);
      if (n.children) walk(n.children);
    }
  }
  walk(tree);
  return map;
}

/** 获取某个元素 ID 对应的所有标签（含祖先层级） */
export function getElementPath(id: string, tree: ElementNode[] = ELEMENT_TREE): string[] {
  function find(nodes: ElementNode[], path: string[]): string[] | null {
    for (const n of nodes) {
      const cur = [...path, n.label];
      if (n.id === id) return cur;
      if (n.children) {
        const r = find(n.children, cur);
        if (r) return r;
      }
    }
    return null;
  }
  return find(tree, []) ?? [id];
}
